### ISSUE TITLE
Question about webpack/babel config

### ISSUE THREAD

**Issue by IrregularShed** [prateekbh/preact-material-components#100]
I've started replacing the components in a project that were based on preact-mdl with preact-material-components (which is why I got involved in the first place!) but I've hit a snag when I'm getting webpack to build the project and, after a few hours of trying everything I can think of, I'm no closer to figuring out what's going on.

The project is based on preact-boilerplate and I've followed the changes made to that to keep on top of things (so it's now Webpack 2 and Jest, not Webpack 1 and Jasmine/Mocha). It's for a client so I can't show the code :(

I replaced the preact-mdl Card with the MDC Card and attempted to build the project, but I got this error:
```
ERROR in ./~/preact-material-components/MaterialComponent.js
Module parse failed: C:\dev\acss-web\node_modules\source-map-loader\index.js!C:\dev\acss-web\node_modules\preact-material-components\MaterialComponent.js Unexp
ected token (57:9)
You may need an appropriate loader to handle this file type.
|       // Components must implement this method for their specific DOM structure
|       materialDom(props) {
|               return <div {...props}>{props.children}</div>;
|       }
|       render() {
 @ ./~/preact-material-components/Card/index.js 4:0-53
 @ ./src/components/partials/ui/card.js
 @ ./src/components/pages/customer/view.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js
```

I've spent ages picking through things, and it looks like `MaterialComponent.js` hasn't been handled by the JSX transformation when building. When I replaced the above return statement with this, it works:
```
    return h('div', Object.assign({}, props), props.children);
```
I'm not sure where to go from here. Do we need to alter the build process of preact-material-components, so that the `MaterialComponent.js` is built, or is the problem entirely within how my project is set up? (I'm not _quite_ out of my depth but it's close.)

**Comment by prateekbh** [comment]
try updating to 1.0.2 version

**Comment by prateekbh** [comment]
fixed with a release, thanks for pointing out
