### ISSUE TITLE
Slider not re-rendered when the value prop changes

### ISSUE THREAD

**Issue by photz** [prateekbh/preact-material-components#1009]
As the title says, I'm using the Slider component and noticed that the thumb stays at its old position when the value prop changes.  I think what's missing is only an implementation of componentWillReceiveProps which checks if the value has changed and calls setValue if necessary?

**Comment by cromefire** [comment]
yes it's missing in `componentsWillUpdate()`

**Comment by prateekbh** [comment]
@cromefire isn't `mdcNotifyProps` for one these things?

**Comment by cromefire** [comment]
Value doesn't behave with it because undefined

**Comment by cromefire** [comment]
@photz if you open a PR quickly with the changes, we can squeeze this into `1.5.3`

**Comment by cromefire** [comment]
Okay I did a PR
