### ISSUE TITLE
"Can't have a focus-trap without a focusable element" in Drawer 

### ISSUE THREAD

**Issue by photz** [prateekbh/preact-material-components#1010]
I just upgraded my app to 1.5.3 from the master branch and the only thing that I haven't gotten to work again is the Drawer component, which raises the following exception:
`index.js?79b7:169 Uncaught Error: You can't have a focus-trap without at least one focusable element`

![focus-trap](https://user-images.githubusercontent.com/856205/45956492-ecd31180-c012-11e8-8037-4c421bf312a0.png)

This also happens when I copy the updated example here:
https://github.com/prateekbh/preact-material-components/blob/master/docs/src/routes/drawer/sample.txt

**Comment by prateekbh** [comment]
yep sorry we're in middle of updating the docs, here's how u can do this:
https://github.com/prateekbh/preact-material-components/blob/master/docs/src/components/menu/index.js#L71-L89

**Note:** One of them has to have `selected` prop.

P.S.: We know its horrible, thus we'll take more control of these components in 2.0

**Comment by photz** [comment]
In the file you referenced the MDComponent property is accessed from outside, but is now protected, so it doesn't compile.

**Comment by cromefire** [comment]
@photz please use an old version or `@ts-ignore` for now 2.0 will solve that

**Comment by prateekbh** [comment]
@cromefire can u fix this I. 1.5.3?

**Comment by prateekbh** [comment]
oh i got what u meant by that, yep lets just wait till 2.0
