### ISSUE TITLE
Fullwidth prop on textfield doesn't do anything

### ISSUE THREAD

**Issue by ForsakenHarmony** [prateekbh/preact-material-components#104]
adding `fullwidth` / `fullwidth={true}` doesn't do anything

**Comment by ForsakenHarmony** [comment]
wait, nvm it works now, but the styles still seem broken

**Comment by prateekbh** [comment]
@forsakenharmony is anything still broken?
Asking because u closed the issue

**Comment by ForsakenHarmony** [comment]
no, I think that was a problem with hot reload

the styles are a problem with `material-components-web` itself
