### ISSUE TITLE
Issue with IconButton

### ISSUE THREAD

**Issue by cbetta** [prateekbh/preact-material-components#1087]
I have the following in place:

```js
import { h, Component } from "preact";

import IconButton from "preact-material-components/esm/IconButton";
import "preact-material-components/IconButton/style.css";

export default class Widget extends Component {
  render() {
    return (
      <div className={style.this}>
        <IconButton>
          favorite_border
        </IconButton>
      </div>
    );
  }
}
```

And I get no errors, yet the style doesn't load.

<img width="435" alt="screenshot 2018-10-10 at 22 59 54" src="https://user-images.githubusercontent.com/7718/46768489-393f7200-cce0-11e8-9e20-dd6b1307adba.png">

I have the feeling this has recently changes, as the docs are vague on it as well and [mention a `IconToggle` instead](https://material.preactjs.com/component/icon-button/). What is the right syntax?

**Comment by cbetta** [comment]
That does not seem to work.

**Comment by prateekbh** [comment]
Ah sorry, did you include the material fonts in ur web app?
```
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

**Comment by cbetta** [comment]
Yes I have that in place too, and Icons are working fine as is

**Comment by cromefire** [comment]
Can you have a look at the DOM?

**Comment by cbetta** [comment]
It seems to not actually wrap the text into an icon.

![screenshot 2018-10-16 at 08 52 33](https://user-images.githubusercontent.com/7718/47000767-dfe0a400-d120-11e8-8754-0ba11c367f2c.png)

**Comment by cromefire** [comment]
I will have a look at that, it seems like there is a missing class

**Comment by prateekbh** [comment]
Sorry this was a bug in our docs, deploying a fix right now.

Here's how the code for this component looks like: 
https://github.com/prateekbh/preact-material-components/blob/master/docs/src/routes/icon-button/index.js#L62-L65

**Comment by cbetta** [comment]
Ah that makes a lot more sense! Tnx!
