### ISSUE TITLE
Module not found: Error: Can't resolve 'preact-material-components/Toolbar/style.css'

### ISSUE THREAD

**Issue by dandv** [prateekbh/preact-material-components#1097]
I have a Preact app generated with the CLI a few months ago, and the standard header/index.js contains

    import 'preact-material-components/Toolbar/style.css';

When upgrading from 1.5.2 to 1.5.3, I get

> Module not found: Error: Can't resolve 'preact-material-components/Toolbar/style.css' in 'src/components/header'.

Is this one of the breaking changes mentioned in #1003? I don't see a "Toolbar" at https://material.preactjs.com/component/, only Top AppBar, but I don't recall if there was a Toolbar there to begin with.

**Comment by cromefire** [comment]
> Is this one of the breaking changes mentioned in #1003?

No that is for `2.0` not `1.5.3`

It got removed here: #1007

Toolbar is deprecated (see [here](https://material.io/develop/web/components/toolbar/)), you should use `TopAppBar` instead. Sorry for the inconvenience we are currently trying to make the transition to new mdc versions less painful

**Comment by liudonghua123** [comment]
I have the same problem.
