### ISSUE TITLE
Card and Primary action

### ISSUE THREAD

**Issue by paulkatich** [prateekbh/preact-material-components#1142]
Does the card component support primary action ? I would like a user  to navigate on click of the card to a new screen. This seems to be supported by material io web component(mdc-card__primary-action).is it included as a feature by this framework. Any plans to implement it ?

**Comment by prateekbh** [comment]
This should be supported in the current version, however looks broken currently.
I can patch this and respond with the link to the documentation in 48 hrs
Cc: @cromefire

**Comment by prateekbh** [comment]
I did it here https://github.com/prateekbh/preact-material-components/tree/master/docs/src/routes/card

With the help of css

**Comment by prateekbh** [comment]
here's updated example and published a new version
https://material.preactjs.com/component/card/

**Comment by paulkatich** [comment]
@prateekbh The buttons are fixed. But material io has the ink ripple effect when you click the image on the card. Is this feature implemented ?

**Comment by prateekbh** [comment]
can you try adding `ripple` prop to the buttons?
