### ISSUE TITLE
Bug on close Drawer

### ISSUE THREAD

**Issue by arma7x** [prateekbh/preact-material-components#1159]
How to close Drawer correctly? The only way is by set dismissible={true} and modal={false} then trigger onClick to close it.

**Comment by cromefire** [comment]
https://github.com/prateekbh/preact-material-components/blob/5ee20a571876fa300788e2f7a8e5cce1b5e3c19e/ts/Drawer/index.tsx#L90
https://material.io/develop/web/components/drawers/#mdcdrawer-properties-and-methods

Get a reference and set `ref.MDComponent.open` to `true` or `false`

**Comment by cromefire** [comment]
Feel free to comment if this does not solve the problem and I'll reopen
