### ISSUE TITLE
TopAppBar and router

### ISSUE THREAD

**Issue by gopalramadugu** [prateekbh/preact-material-components#1161]
I created an app with topaapbar and some basic routing functionality ex: when I click a submit button on the form the app goes to next page. I see a small issue with top app bar. The top app bar title is stale and still shows the old page title on the top app bar. Is there a way to change this behavior to reflect the correct page title on top app bar when I use preact router.

**Comment by cromefire** [comment]
The router has some kind of `onChange` event listener and or you can change it on button press.
To change the TopAppBar title you just need to change the text in `TopAppBar.Title`
e.g:
```TypeScript TSX
[...] 
<TopAppBar.Title>
    {this.state.title}
</TopAppBar.Title>
[...] 
```
Then to change the title:
```TypeScript TSX
this.setState({title: "Some Page"});
```

Please either close the issue, if this helps, or ask more specifically.

**Comment by gopalramadugu** [comment]
I tried below but the title doesnt change. The handle submit function gets invoked on click of button. 



```
   <TopAppBar.Title>{this.state.toolbarTitle}</TopAppBar.Title>

    handleSubmit = () => {
 
		this.setState({toolbarTitle:'testing'});
        route('/lawnmowing');
    };
```

**Comment by prateekbh** [comment]
I can see the title changing. What's wrong?

**Comment by cromefire** [comment]
But only in module view some how

**Comment by cromefire** [comment]
![screenshot](https://user-images.githubusercontent.com/26320625/49356127-ea53fe80-f6ca-11e8-915f-4b5b4194ae32.jpg)
As you see I pressed the right one

**Comment by cromefire** [comment]
Tested in Firefox, if that matters

**Comment by gopalramadugu** [comment]
@prateekbh Just wanted to see if you had chance to look in to this. Any other suggestions to fix this ?

**Comment by cromefire** [comment]
I had also problems with `hmr` and rerendering

**Comment by cromefire** [comment]
I tested it again with chromium and firefox desktop and it does work in chromium, but not in firefox.

I changed it to only use html5 elements and no mwc at all, but it still does not work. I will report that to preact.

**Comment by cromefire** [comment]
developit/preact#1270

**Comment by cromefire** [comment]
Okay this bug was related to a thing in the code sandbox template, I will setup a template myself and look if it works

**Comment by cromefire** [comment]
See preact bug
