### ISSUE TITLE
Switch not responding to props change

### ISSUE THREAD

**Issue by eligao** [prateekbh/preact-material-components#1189]
When the props (`selected `, `disabled`) changes after a Switch component is initiated , it does not change its shape accordingly, thus I cannot create a controlled Switch.
The props only affects the initial render of a Switch.
A quick example to reproduce the bug: 
https://codesandbox.io/s/jvkx6zoj75

This might be caused by the upstream as stated here:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch#initially-disabled-switch
Maybe we should use `MDCSwitchFoundation.setDisabled` and `MDCSwitchFoundation.setChecked`?

**Comment by prateekbh** [comment]
Thanks for the repro.. will look into it

**Comment by eligao** [comment]
I've already created a PR addressing this #1190

**Comment by cromefire** [comment]
@prateekbh the pr is ready to be merged

**Comment by prateekbh** [comment]
taking a look now
