### ISSUE TITLE
TextField Safari: cursor position resets to end of text input whenever value changes

### ISSUE THREAD

**Issue by johnhaitas** [prateekbh/preact-material-components#1192]
In Safari, whenever editing the value in a `TextField`, the cursor position jumps to the end of the line.

something like the following will reproduce the bug (using `linkstate` for simplicity
```javascript
<TextField type="text"
	className={style.firstName}
	id="profileFirstName"
	name="profileFirstName"
	label="First Name"
	value={form.firstName}
	onInput={linkState(this, 'form.firstName')}
/>
```

A PR ~~has already been created for `material-components/material-components-web` https://github.com/material-components/material-components-web/pull/4160~~ is here: #1193

**Comment by cromefire** [comment]
Well what should we do about that? It's an mdc bug, so there's nothing we can do.

I'll close this, but feel free to comment, if I miss understood you.

**Comment by cromefire** [comment]
Sorry I just saw that we where also doing this
