### ISSUE TITLE
Textfield and full width

### ISSUE THREAD

**Issue by gopalramadugu** [prateekbh/preact-material-components#1194]
If I use the text field and add fullwidth ={true}. The style reverts to plain background instead of white smoke which is the default background color for the div. This looks like a bug.

**Comment by cromefire** [comment]
We don't change anything in the styles, that is something the mwc did.

You can:
- fix it your self by overriding it with css
- report a bug (if there isn't already one) at [the mwc bug tracker](https://github.com/material/material-components-web/issues)

Would recommended both.

**Comment by cromefire** [comment]
Tell me if I got it wrong, but closing it for now
