### ISSUE TITLE
Menu trigger

### ISSUE THREAD

**Issue by lukeed** [prateekbh/preact-material-components#121]
New additions are fantastic! 

I noticed a slight bug on the [Menu Demo](https://prateekbh.github.io/preact-material-components/#/component/menu). If you click **only** the trigger repeatedly:

1. Open
2. Close
3. Nothing
4. Nothing
5. ...

The "closed" state only resets if you click on a `MenuItem` or `document.body`. I'd expect the menu to toggle states on every click.

I'm not sure if this is pertinent only to the demo or it's part of the component.

Thanks!

**Comment by prateekbh** [comment]
fixed and published to the docs site 😃

**Comment by lukeed** [comment]
Amazing! 🎉
