### ISSUE TITLE
Add Theming support on README

### ISSUE THREAD

**Issue by ooade** [prateekbh/preact-material-components#123]
It would be nice to let users know that they can change the look of things around. I don't know but I think it's one of the main reasons MDC succeeded over MDL. [Here](https://github.com/material-components/material-components-web/blob/master/docs/theming.md)'s how to go about [themeing](https://github.com/material-components/material-components-web/blob/master/docs/theming.md).

**Comment by prateekbh** [comment]
Hi! thanks for the suggestion, do you think we should add a link in readme to this file or a small writeup about the same would with the link included would make more sense?

**Comment by ooade** [comment]
Writing a small writeup with the link included is better :muscle: 
But, adding an example will be a lot better tho :sweat_smile: 
## WDYT?

**Comment by prateekbh** [comment]
I guess this is awesome, 
Since the base theme of docs are already there, I am expecting if someone can take this up and PR. However if not i'll take this up in some days. Just running a lil bz with some project

**Comment by ooade** [comment]
@prateekbh I've bin a little busy with school these days. Is there any way to test things around this repo?

**Comment by prateekbh** [comment]
there is a folder named sample

**Comment by ooade** [comment]
Okay :)

**Comment by MobiusHorizons** [comment]
@prateekbh, on the subject of theming, it looks like the sass is already compiled to css in the library build step, so the web project which includes `preact-material-components` can't change those theme sass variables. on super new browsers, you can use css variables to do it, but it still loads wrong initially. What is the strategy for theming.

**Comment by prateekbh** [comment]
@MobiusHorizons honestly I haven't had enough free cycles to think over this.. Will try to work on this in a week

**Comment by filoozom** [comment]
@MobiusHorizons ```.scss``` files are still available for every component in ```node_modules/@material```, and we can copy them over without any issues. Just need to slightly edit [CssMigrationWebpackPlugin.js](https://github.com/prateekbh/preact-material-components/blob/master/CssMigrationWebpackPlugin.js) and compile the SASS ourselves.

**Comment by prateekbh** [comment]
@MobiusHorizons can you explain "_but it still loads wrong initially._"

we can add .scss files to ever component +  the root one, if that makes lives simpler.

**Comment by MobiusHorizons** [comment]
@prateekbh, the css contains hardcoded theme colors, so it shows those on firstload until the css that sets the css variables runs. For example:
```
:root {
 --mdc-theme-accent: /* secondary color */;
 --mdc-theme-primary: /* primary color */;
}
```

The above also only works on very new browsers as seen here: http://caniuse.com/#feat=css-variables

As to adding the scss files, that is probably the way to go, but would require experimentation / special webpack setup.

**Comment by prateekbh** [comment]
>require experimentation / special webpack setup
but since you are using it in your webpack scss project shouldn't it just work out of the box?

**Comment by MobiusHorizons** [comment]
Most configurations I have seen exclude `node_modules` by default. I'm sure it's doable, but it's unlikely to just plug and play.

**Comment by wuweiweiwu** [comment]
@prateekbh Can I pick this up :)

**Comment by prateekbh** [comment]
@wuweiweiwu can you pick up #660 before anything its a blocker for any further releases

**Comment by wuweiweiwu** [comment]
@prateekbh Sure! :)

**Comment by prateekbh** [comment]
https://material.preactjs.com/component/theme/
