### ISSUE TITLE
Show TopAppBar with scroll 

### ISSUE THREAD

**Issue by gopalramadugu** [prateekbh/preact-material-components#1239]
Can we make the TopAppBar visible with scroll ? This is useful if I have a page that might need scroll. I dont want the user to scroll to top to open menu again. I tried couple of css with position fixed and z-index none seem to work. Am missing a property setting ?

**Comment by cromefire** [comment]
Cc: @prateekbh

**Comment by cromefire** [comment]
I think this was resolved by the `fixed` prop on the docs site
