### ISSUE TITLE
Label and fullwidthTextField

### ISSUE THREAD

**Issue by gopalramadugu** [prateekbh/preact-material-components#1241]
I am getting below warning in console and this seems to be messing up the rendering of the component. Is this a bug or a know restriction ? I have an address field which uses the full width property. Can you please guide me here ? 

Passing a "label" prop is not supported when using a "fullwidth" text field.

**Comment by gopalramadugu** [comment]
Thank you @prateekbh. I have one more question. During navigation If I visit a page multiple times on few occasions I am getting below error. This seems to happen If I set state on loading of the page. The this.MdComponent seems to be set to null. I am setting the state in componentDidMount. 

Uncaught (in promise) TypeError: Cannot set property 'value' of undefined
    at TextFieldInput.componentWillReceiveProps (index.js:81)
    at setComponentProps (preact.mjs:464)
    at buildComponentFromVNode (preact.mjs:632)
    at idiff (preact.mjs:257)
    at innerDiffNode (preact.mjs:355)
    at idiff (preact.mjs:292)
    at diff (preact.mjs:218)
    at renderComponent (preact.mjs:573)
    at setComponentProps (preact.mjs:480)
    at buildComponentFromVNode (preact.mjs:632)

**Comment by gopalramadugu** [comment]
To be more specific this happens when I have child component that has a text field and I set the state in parent componentdidmount for the child component and pass the state as props.

**Comment by gopalramadugu** [comment]
@prateekbh 
Below is the codesanbox. I am using router and setting state from query parms. Can you please help me with this ?

https://codesandbox.io/s/xv0rrx62n4

**Comment by gopalramadugu** [comment]
The issue seems to be specific to componentdidmount. If I set state in constructor I dont see same issue.

**Comment by cromefire** [comment]
There is a missing condition

**Comment by gopalramadugu** [comment]
@cromefire  Can I please know when this is scheduled for release ?

**Comment by prateekbh** [comment]
today
