### ISSUE TITLE
2.0 - Root component should export all members

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#1244]
A component should export all of its members, user shouldn't have to specify a path to access any sub member.

e.g.
https://github.com/prateekbh/preact-material-components/blob/2.0/packages/docs/src/routes/chips/index.js#L6-L8

**Scope:** All components

**Comment by cromefire** [comment]
It's to have less overhead, webpack should filter it out, but I don't know if everything has tree-shaking

**Comment by prateekbh** [comment]
Yep but it makes it super unintuitive.
Most compilers/bundlers have tree shaking now, if not thats the users choice to have a bundler which does not do a very basic thing

**Comment by prateekbh** [comment]
This is mostly fixed now
