### ISSUE TITLE
FormField vs Formfield

### ISSUE THREAD

**Issue by cedric-marcone** [prateekbh/preact-material-components#125]
Hello,

As seen in https://github.com/developit/preact-cli/issues/42, there's a small inconsistency in the documentation regarding the Formfield component.

In the documentation, it's always imported the following way :
```js
import FormField from 'preact-material-components/FormField'
```

But, with preact-cli, we need to import it from the global exports : 
```js
import {Formfield} from 'preact-material-components'
```

The thing is that it's error prone as it's advertized as "FormField" but it's exported as "Formfield" (with a lower case "f").

Great work BTW !
Thanks.

**Comment by prateekbh** [comment]
Hey, thanks for using `preact-material-components`!!!
It turns out this was a silly typo in docs only and worked with me because Mac 😛 .

I have updated the docs, hope it doesn't cause much inconvenience  to you.
