### ISSUE TITLE
2.0 - Add gesture support to drawer

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#1251]
We need to add support for swipe gesture to our modal drawer, because its 2019.

**Comment by prateekbh** [comment]
@developit has the script to do this. we just have to ask for it and paste it here I guess.
Otherwise we can evaluate something like hammer/tocca.js

**Comment by cromefire** [comment]
@prateekbh I just tried `hammer.js` and it would also work: https://gist.github.com/cromefire/8a5e69f61d69d165f9988a63d0b78645

**Comment by prateekbh** [comment]
right, i'd like to take a look at @developit 's script as well as I know that comes without dependencies

**Comment by developit** [comment]
@cromefire @prateekbh sorry about that - it's here:
https://gist.github.com/developit/a78fceed440b98e62582e4440b86bfab

**Comment by cromefire** [comment]
Thanks

**Comment by cromefire** [comment]
But I thing we should make this either opt in or opt out (I would prefer opt out; So that it is seperated from the original drawer)

**Comment by prateekbh** [comment]
@developit @cromefire I don't know if this is a bad or a good news but mdc-web dropped support for even closing the drawer with gesture.. 🤣 
Dropped support for such basic use cases is what made us re-think our position of opnionless wrapper over mdc-web

**Comment by developit** [comment]
Probably good news, it was annoying to disable swipe close gestures.

**Comment by cromefire** [comment]
Merged into 2.0
