### ISSUE TITLE
Select component Name and ID

### ISSUE THREAD

**Issue by gopalramadugu** [prateekbh/preact-material-components#1279]
I am trying to mention name on select component. But the name doesnt appear in the html. This is same for ID as well. Is this by design ? Is there a way to display error message for select ? Like Textfield has a valid option. The mdc does has a valid option. 

https://material.io/develop/web/components/input-controls/select-menus/

**Comment by gopalramadugu** [comment]
https://codesandbox.io/s/246zm2rp0

Above is the code for valid which doesnt seem to be working.

@cromefire @prateekbh

**Comment by cromefire** [comment]
After the PR is merged and released you can use the `controlProps` prop

**Comment by prateekbh** [comment]
published 1.5.7
