### ISSUE TITLE
Select onChange handler

### ISSUE THREAD

**Issue by cedric-marcone** [prateekbh/preact-material-components#128]
Hello again, 

Would you mind adding selectedOptions and selectedIndex when calling the event handler ?

```js
this.props.onChange(
  this.MDComponent.selectedOptions,
  this.MDComponent.selectedIndex
);
````

It could let us write more generic code, without ```refs```tricks ;)

```js
selectedChanged = (name) => (values, i) => {
   console.log(name, i, values)
   this.setState({ [name]: i })
}

render() {
 return (
    <Select onChange={this.selectedChanged('chosenOption')}>
    ...
  )
}
```

**Comment by prateekbh** [comment]
Hey! Its a pretty easy thing to be done. What prevents me from doing that in first place is that I wanted to keep this as opinion-less and transparent as I can. so whatever event `material-components-web`(which is nothing as of now) fires gets triggered in `preact-material-components`. Do you think it'll be better to open an issue [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select) instead?

That will help not only `preact-material-components` but also other framework wrappers.

**Comment by cedric-marcone** [comment]
I understand your concern but, I think ```material-design-components``` natural way of querying the DOM to find what was selected doesn't sound correct in (p)react : using refs to do the same seems fragile.
Not firing an event with target values (or index) seems like a design decision on their part which could lead to lengthy discussions :)

**Comment by prateekbh** [comment]
OK, how about this. preactMaterialComponent can yield the index, since that should be available in MDComponent. But i am not sure if there is anything apart from this that i can pass in as `values`(as suggested in above example by you).

**Comment by cedric-marcone** [comment]
MDComponent seems to have the following  properties :
- selectedIndex containing the last selected index
- selectedOptions containing the array of items selected (since it can be a multiple selection)

That's why I proposed to emit both properties :)

But, I understand your concern : we don't have any abstractions to dynamically extract values or labels.

That's why it should be the developer responsibility to add any attributes he needs on each item for values and can rely on textContent for labels.

What do you think ?

**Comment by prateekbh** [comment]
will try to fix this soon

**Comment by prateekbh** [comment]
right, this was changed to native event.
deploying the fixed documentation right now.

you can use `e.target.selectedIndex`
