### ISSUE TITLE
Use Renovate or similar

### ISSUE THREAD

**Issue by kontrollanten** [prateekbh/preact-material-components#1285]
Thanks for a great package!

What do you think about installing Renovate or something similar, to keep the MDC packages up to date?

I just upgrade webpack in my project and the Dialog got broken because webpack changed (fixed?) dependency resolving, so that @material/dialog got updated to latest release (with a new API). If we try to keep this package dependencies up to date, I guess it can help some people to track errors and get new features.

**Comment by cromefire** [comment]
We have greenkeeper in place, but mdc explicitly ignored, because it is a huge effort to update them, that's why we:

a) do this manually
b) don't do this for every update

2.0 will deliver the latest and greatest version of mdc

**Comment by cromefire** [comment]
[Yarn](https://yarnpkg.com) should handle the resolution correctly, so please consider that

**Comment by cromefire** [comment]
Please let me know if that didn't solve the problem

**Comment by kontrollanten** [comment]
yarn is no alternative because it crashes other parts. But I think I've got it working by changing `package-lock` manually. Thanks for quick response.

**Comment by cromefire** [comment]
This is more of a npm problem than webpack, that's why I always directly create projects with yarn

**Comment by cromefire** [comment]
Also `yarn import` may help you migrating without crashes
