### ISSUE TITLE
HMR and event handlers

### ISSUE THREAD

**Issue by cedric-marcone** [prateekbh/preact-material-components#129]
Hey ! ...me again :)

In https://github.com/developit/preact-cli HMR is active and it doesn't play well with the event handlers you're binding.

I think the reason is you're attaching them in ```componentDidMount``` but they are never cleared in ```componentWillUnmount```.

Do you accept PRs ?

**Comment by prateekbh** [comment]
yes I love PRs... please feel free to go ahead and open one

**Comment by cedric-marcone** [comment]
Hmm, I'm banging my head on this one !! :)
Even when I "unlisten" the event handler in componentWillUnmount it continues to be called once per reload via HMR...
I'll continue to investigate tonight and if I fail miserably I'll commit my changes in the fork tomorrow morning.

If you have the opportunity to review it and give me some insight, I'll be grateful :)  

I keep you updated.

**Comment by cedric-marcone** [comment]
OK, I really don't know what's going on here, I'm way too noob on preact / HMR...
Could you take a look at https://github.com/cedric-marcone/preact-material-components/commit/96a2f0dc59907f4edc1df94d761b912aa89f07d7 and tell me what you think ?
Nothing big going on there, but it really doesn't work : every time I update the code of a  component displaying a ```Select``` an onChange handler is added, even if it seems to be correctly unregistered.

**Comment by prateekbh** [comment]
Ha no probs, i'll take in the morning

**Comment by prateekbh** [comment]
@cedric-marcone can u do me a favor... Can u set up hmr in a separate repo for me.
And add the instructions to run hmr in readme?

**Comment by cedric-marcone** [comment]
Here it is :
https://github.com/cedric-marcone/preact-material-components-test

To setup HMR I didn't do anything more than using preact-cli, the interesting piece is in ```routes/home/index.js```

The README explains how to reproduce the bug.

**Comment by prateekbh** [comment]
thanks will look into it

**Comment by prateekbh** [comment]
ok cool had a look, so its not about `unlisten` as the root element itself gets destroyed. But the MDCComponent itself gets initialized multiple times and thus emitting multiple events.
Just in case if you wanna PR this, on the eaxct same place you called `unlisten` you need to replace the line to 
```js
this.MDComponent.destroy();
``` 
and this should fix it for you

**Comment by cedric-marcone** [comment]
Of course !! That makes sense.
I prepare a PR.
Thanks a lot.

**Comment by cedric-marcone** [comment]
Thanks for the merge !

**Comment by prateekbh** [comment]
Cheers! will release ASAP

**Comment by prateekbh** [comment]
@cedric-marcone hey! I just released the new version.
can you please verify if this works for you

**Comment by cedric-marcone** [comment]
I updated the test project (https://github.com/cedric-marcone/preact-material-components-test) to reflect changes in #129 and #128.
=> It works perfectly, thanks for your commitment.
