### ISSUE TITLE
Where are the docs located?

### ISSUE THREAD

**Issue by staydecent** [prateekbh/preact-material-components#131]
I noticed a typo or two I was hoping to PR for.

Also, I can't for the life of me figure out how to get the floating labels working with the text field. Passing `label='something'` does nothing on my `<Textinput ... />`.

Was hoping to look at the unbuilt source for the examples to see how it was done.

**Comment by prateekbh** [comment]
Hi!
can you please try and tell if this does not work

```jsx
import {h, Component} from 'preact';
import Textfield from 'preact-material-components/Textfield';
import 'preact-material-components/Textfield/style.css';

export default class TextfieldPage extends Component {
  render(){
    return (
      <div>
        <Textfield label="somelabel"/>
      </div>
    );
  }
}
```

**Comment by prateekbh** [comment]
Also the docs are here: prateekbh.github.io/preact-material-components/

**Comment by cedric-marcone** [comment]
You can find the docs on the ```gh-pages```branch.
Take a look over there : 
https://github.com/prateekbh/preact-material-components/tree/gh-pages

**Comment by prateekbh** [comment]
@staydecent were you able to find the docs/ resolve your error?

**Comment by staydecent** [comment]
Yup found the source of the docs. Thanks! I'm deep in a client project
right now and will need a week before I can test out getting the floating
labels to work.

Appreciate the work on this! Look forward to replacing my usage of MDL with
it soon.

**Comment by prateekbh** [comment]
closing this, please re-open if you have any further questions
