### ISSUE TITLE
Component/index.js commited

### ISSUE THREAD

**Issue by cedric-marcone** [prateekbh/preact-material-components#134]
Hey, I don't know why but, when I build the project all the index.js files are different from those in the repo, even if I didn't touch the matching jsx file.

The two main differences are : 
1. The _extends function which is a generated as a one liner on my machine.
2. The call to _extends which is not indented the same way.

As these files are in the git repo I can't just commit my changes without taking extra care of not committing the compiled version of the jsxs.

Do we really need to publish them to git ?

**Comment by prateekbh** [comment]
Ahhh sry, thats a pending task on me, you can commit them. Prettier will take care of them

**Comment by prateekbh** [comment]
@cedric-marcone you can commit these changes for now, a new version of prettier is expected, after which prettier can be run after webpack and you wont see this.

The new version basically allows you to skip node modules, which might take a little too long if I added them now.

**Comment by cedric-marcone** [comment]
Thanks, I definitely  thought ```Prettier``` would be involved in your answer ;)
