### ISSUE TITLE
enhanced: mdc web migration

### ISSUE THREAD

**Issue by TroyTae** [prateekbh/preact-material-components#1343]
Hello, thank you for your maintaining :)

Now I'm using preact and mdc in my side project.
So I found this project, but this project still used v0.39.0.

Is there any plan about migration?
Or is there something I can do to help?

**Comment by cromefire** [comment]
Well 2.0 is kind of ready since a long time. But there were a few missing pieces and I and @prateekbh had little time.

**Comment by cromefire** [comment]
Well 2.0 is kind of ready since a long time. But there were a few missing pieces and I and @prateekbh had little time.

**Comment by TroyTae** [comment]
@cromefire 
Thank you for your reply.
Is there an list about missing pieces?
If the missing pieces can solve by contributor(as you know some issue can solve only collaborator),
I wanna help this project!

**Comment by prateekbh** [comment]
#1335 is one of the biggest blockers that we have right now. It can all be as simple as "the tests are flaky"

**Comment by TroyTae** [comment]
@prateekbh 
Cool! I'll try to tackle that!

**Comment by cromefire** [comment]
And there are a few issues left concerning components (their title starts with `2.0`)

**Comment by TroyTae** [comment]
@cromefire 
Is it an issue with the name `2.0 - **`, correct?
Thank you :)

**Comment by cromefire** [comment]
Yes there is #1262, #1263, #1267, #1268 and #1270 from what I see

**Comment by cromefire** [comment]
But the completely new ones (the first two) aren't as important as the rest right now

**Comment by Mateiadrielrafael** [comment]
@cromefire Is there any estimated release date for 2.0?

**Comment by cromefire** [comment]
No. When it's ready I guess @prateekbh will release it
