### ISSUE TITLE
Should we use named export instead of default export?

### ISSUE THREAD

**Issue by Holi0317** [prateekbh/preact-material-components#137]
Currently, some components like List component need to export more than one components in its package. This make the whole package use a [commonJS way](https://github.com/prateekbh/preact-material-components/blob/3f7c1a884c517363d894d8aaafb658642979b81d/List/List.jsx#L170-L179) to export components. This is not ideal as consumers need to use ugly syntax like `<List.Item />` to consume components. Bundle tools like webpack cannot do tree shaking and may increase bundle size.

Named exports can solve those issues plus reduce typo chance for consumers. But that would be a huge breaking change. Should we migrate to named export and deprecate default export?

**Comment by prateekbh** [comment]
hi! thanks for trying `#PreactMaterialComponents`.
So the answer to your question is two fold.
1. even if we do the suggested webpack is unable to treeshake completely. (https://github.com/webpack/webpack/issues/2867)
2. imagine a scenario where you are importing menu and select both and both of them export `{Item}`. In that case the current set will do a name clash.

Though both of the above can be solved, I am willing to do a major version upgrade once case 1 is solved.

**Comment by cromefire** [comment]
Named import is possible since `1.5.1` now and I am looking forward to make that optional, which shouldn't break anything. Also the webpack thing seems to be fixed and name clashing is also prevented.

**Comment by cromefire** [comment]
We should remember this for `2.0`

**Comment by prateekbh** [comment]
Fixed for 2.0
