### ISSUE TITLE
Drawer Component

### ISSUE THREAD

**Issue by paulinhapenedo** [prateekbh/preact-material-components#140]
Hello!

I've been having some problems with the Drawer component. I want to keep the Drawer component always open, so I thought of using the PermanentDrawer ou even the PersistentDrawer, but none seem to work properly. 

Is there a way to keep the Drawer component always open? Some props, maybe? 

Thanks!

**Comment by prateekbh** [comment]
Hi!
can you give a little description of what form factor(mobile/desktop/tab) are you testing on?
Also what is not working properly? are your drawers getting closed or does it appear broken?

btw `PermanentDrawer` should be thing to be used here

**Comment by prateekbh** [comment]
hey @paulinhapenedo , there has been a recent bug fix for persistent drawer, can you please update and try the same now.

Please reopen if this seems to still not work for you.
