### ISSUE TITLE
What is proper way to set an initial value on TextField component?

### ISSUE THREAD

**Issue by kbrownhbs** [prateekbh/preact-material-components#145]
The component does not have setter for initial input value.  

Setting input via javascript DOM manipulation works but  the floating label does not float to the top.  Inspecting the input I see that "mdc-textfield--upgraded" would need to be added to the containing div to make DOM manipulation work.  

However it would probably be better to add a setter of initial value directly on TextField component similar to the "checked" getter/setter provided for Checkbox component.

**Comment by prateekbh** [comment]
hi!
For setting the input value please use `value='test here'` as it directly applies to the input.

As far as floating label is concerned, it is a valid bug, will fix it in the next update.

**Comment by kbrownhbs** [comment]
Thanks for the quick response...I tried setting value as well.  Had the
same issue.  The issue may have something to do with the shadow dom.

On Sun, Jun 4, 2017 at 10:09 PM, Prateek Bhatnagar <notifications@github.com

**Comment by prateekbh** [comment]
@kbrownhbs are you using any form of web components?
cuz `react-material-components` does not have anything to do with shadow dom.

**Comment by kbrownhbs** [comment]
No I'm not using web components.  Just saw something in Chrome dev tools that led me to think shadow was being used by your components...my prior statement was likely inaccurate, as I don't know much about web components.

![image](https://cloud.githubusercontent.com/assets/3537923/26772470/9def83ce-4993-11e7-9cba-d7515f0d1497.png)

**Comment by kbrownhbs** [comment]
Thanks a lot...will you be updating NPM shortly with a new release?

**Comment by prateekbh** [comment]
yeah will do it in a day or two...

**Comment by kbrownhbs** [comment]
Verified linear progress addressed #145.

Your fix worked like a charm.  Thanks!

**Comment by prateekbh** [comment]
just released the new package 😄 
thanks for using `preact-material-component`
