### ISSUE TITLE
Build errors out-of-the-box with Webpack 2 and UglifyJS

### ISSUE THREAD

**Issue by ethanroday** [prateekbh/preact-material-components#150]
Steps to reproduce:
1. Create a new app using `preact-cli`
2. Run `npm i -D preact-material-components`
3. Add `import Button from 'preact-material-components/Button';` in `src/app.js`
4. Run `npm run build`

Result:

    bundle.js from UglifyJs
    Unexpected token: name (Button) [bundle.js:553,6]

This issue (or similar ones) can also be reproduced in both [preact-boilerplate](https://github.com/developit/preact-boilerplate) and [PreactSimpleStarter](https://github.com/ooade/PreactSimpleStarter). These are easier to play around with since they expose their Webpack configs.

It appears to be due to UglifyJS's lack of support for ES6. However, adding `/node_modules/preact-material-components` to `babel-loader` in Webpack config just results in different unexpected token errors.

#77 seems to imply that there is a UMD version for those of us targeting ES5. How do I make sure my build process picks that up?

**Comment by prateekbh** [comment]
@ethanroday look out for https://github.com/developit/preact-cli/pull/117
It fixes your above said problem

**Comment by ethanroday** [comment]
Will do. For now, though, turns out that I needed to add the following folders to the Babel loader:
- `/node_modules/preact-material-components`
- `/node_modules/@material`
- `/node_modules/material-web-components`
Thanks for the quick reply.
