### ISSUE TITLE
Drawers: PermanentDrawer not properly named

### ISSUE THREAD

**Issue by ethanroday** [prateekbh/preact-material-components#156]
`<Drawer.PermanentDrawer>` is actually getting rendered as `mdc-persistent-drawer`. Looks like it may be a bug here:
https://github.com/prateekbh/preact-material-components/blob/master/Drawer/Drawer.jsx#L210

**Comment by prateekbh** [comment]
woops sry for that, do you wanna PR, else I'll do it ASAP

**Comment by ethanroday** [comment]
#157
