### ISSUE TITLE
Select: default first option and too small width

### ISSUE THREAD

**Issue by keemor** [prateekbh/preact-material-components#165]
In this example https://prateekbh.github.io/preact-material-components/#/component/select
First minor thing is missing closing `</div>`

I think select should get the width of hintText, because now  you'll see only 'Sele'. 
Setting width via `<Select width={{width: 200}} >` does not work

Another thing is how to set first option by default.

The only way I figured out is:

```
export default class SelectPage extends Component {
    constructor() {
        super();
        this.state = {
            chosenIndex: '0'
        };
    }
```
To set chosenIndex as String, setting as Number doesn't work

```
    constructor() {
        super();
        this.state = {
            chosenIndex: 0
        };
    }

```

Thanks for great work :+1:

**Comment by prateekbh** [comment]
Hi, thanks for trying out `preact-material-components`
I am in process of fixing the `div`, great catch thanks :)

As far as the width is concerned, i guess mdc-web(https://github.com/material-components/material-components-web/tree/master/packages/mdc-select) repo would be a better place to open this

And I just checked for the selectedIndex problem the following is working for me, can you please try again:
```
<Select hintText="Select" selectedIndex={1}>
.
.
</Select>
```

**Comment by keemor** [comment]
Hi,
selectedIndex={1} sets 2nd option, not 1st one:
https://www.webpackbin.com/bins/-KnsE8LI4taX5ejSjmeS

**Comment by prateekbh** [comment]
yes because it starts form 0

**Comment by keemor** [comment]
selectedIndex={0} doesn't work

**Comment by prateekbh** [comment]
this i can check 👍 , will revert in a while

**Comment by prateekbh** [comment]
please update and check, you will be able to do it now :)

**Comment by keemor** [comment]
Works :+1:  Thanks
