### ISSUE TITLE
Feature request: List.LinkItem should extends Link (preact-router)

### ISSUE THREAD

**Issue by thibaultsavary** [prateekbh/preact-material-components#177]
When navigating using
```jsx
<a href="/somePath">Link</a>
```
```jsx
<List.LinkItem href="/somePath">Link</List.LinkItem>
```
**The whole app is rendered again.**

When navigating using
 ```jsx
<Link href="/somePath">Link</Link>
```
```jsx
<List.Item onClick={() => route('/somePath')}>Link</List.Item>
```
**Routing works as expected for a SPA**

Would it be possible to either extends the `Link` component from `preact-router` or provide the same behavior when navigating, as well as the `activeClassName` for `List.LinkItem` as well as the other link components if there are others  ?

**Comment by filoozom** [comment]
Should this really be included in this repo though? Preact can also be used with other routers, and this package doesn't depend on ```preact-router```, so I think it might be better to just use ```onClick``` or extend the component yourself?

**Comment by thibaultsavary** [comment]
I agree with the separation concern.

However, because the `List.LinkItem` is semantically a link it should support navigation in a SPA, or not exist at all if it doesn't bring anything more than an `List.Item`.

I proposed to either directly re-implement preact-router `Link` behavior (not a fan of this idea)
or
Make this package depend on `preact-router`, but as you said, there may be people using other routers so it would result in bigger bundle for them.

The problem with the `onClick` technique is that's it's not good for SEO and it adds a listener where a simple `href` attribute solve both problem. (Seems that `Link` from `preact-router` is using the `onClick` method to work in SPA, but keep the href attribute to allow SEO).

Maybe the proposition should be to remove this sub-component if either of the propositions above sounds like separation concern breaking.

**Comment by filoozom** [comment]
And wouldn't something like:
```js
class PreactRouterLinkItem {
	_onClick(e) {
		// route + prevent(e)
	}

	render({ children, href }) {
		return <List.LinkItem href={href} onClick={this._onClick}>{children}</List.LinkItem>;
	}
}
```
do the trick?

**Comment by thibaultsavary** [comment]
Yep that's almost exactly what I ended up with after reading `preact-router` implementation.

**Comment by filoozom** [comment]
Right, but shouldn't that be enough then? You can fairly easily plug in any router you want without the library depending on it. Maybe we could add this example to the documentation, but I don't quite think that this belongs in this package.

**Comment by prateekbh** [comment]
I kinda agree with @filoozom because more prople use `react-router` than `preact-router`.

>The problem with the onClick technique is that's it's not good for SEO and it adds a listener where a simple href attribute solve both problem.

The best part with this is you can put and href and prevent event's default and still call 
```
route(event.tartget.getAttribute('href'))
```
