### ISSUE TITLE
Select component only supports full fidelity js component

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#18]
We should add support for basic component as well

**Comment by Download** [comment]
Can you elaborate? What do you mean exactly?

**Comment by prateekbh** [comment]
@Download  `material-components-web` has two versions of a `select` component.
a. full fidelity js component
b. basic css only 

currently i have only implemented the first one.
just need to copy paste and cleanse the DOM from the mdc repo and flag guard it based on a prop.

**Comment by Download** [comment]
Thanks I get it now

**Comment by prateekbh** [comment]
PR #73 fixes this
