### ISSUE TITLE
Dialog appears to be broken

### ISSUE THREAD

**Issue by ethanroday** [prateekbh/preact-material-components#193]
The dialog examples at https://prateekbh.github.io/preact-material-components/#/component/dialog don't seem to be working (on Chrome 59 and Windows).
Similarly, copying and pasting the demo code into my own preact app doesn't work.

**Comment by prateekbh** [comment]
will look into it asap

**Comment by prateekbh** [comment]
@ethanroday please update, a new version has been just published

**Comment by ethanroday** [comment]
Looking good! Thanks.
