### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by filoozom** [prateekbh/preact-material-components#195]
The library should contain a testing framework to make sure that all components are rendered correctly and exactly like ```material-components-web```.

**Comment by prateekbh** [comment]
there's a project called `preact-render-spy`. WDYT?

**Comment by filoozom** [comment]
Looks nice, will see if I can make something happen. Won't have time for the next few weeks though, so maybe later.

**Comment by filoozom** [comment]
Do you think that snapshot testing would be a good solution for this library? Would make sure that the output stays the same for every update, but we'd still need to make sure that the HTML is the same as ```material-components-web```.

**Comment by prateekbh** [comment]
the same code thing would be easy to do with the render spy thing. not sure about the snapshot thing

**Comment by filoozom** [comment]
I don't really like testing for "same exact code" because HTML can be exactly the same by being "different":

```html
<div class="a b c" style="width: 20px; height: 20px;">
```

is the same as
```html
<div style="height: 20px; width: 20px" class="c b a">
```

Maybe we should compare the result of the ```h``` function?

**Comment by M-ZubairAhmed** [comment]
hey ! I have got some simple solution for this do you guys mind if I make a pr for this ?

**Comment by filoozom** [comment]
Hey, not at all! Please do, I didn't quite find enough time to start this, but I can help you for sure if you need me.

**Comment by prateekbh** [comment]
easiest would be to do visual diff testing with the documentation with puppitier.
also if this needs lets point documentation to latest build components

**Comment by prateekbh** [comment]
Closing this one as we have visual diff tests now!

Thanks for all the efforts and time @filoozom  @M-ZubairAhmed
