### ISSUE TITLE
Merge 3 types of drawers into 1 component

### ISSUE THREAD

**Issue by plusCubed** [prateekbh/preact-material-components#200]
Because all 3 types (permanent, persistent, and temporary) have the [same base CSS](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/_mixins.scss), I think it would make sense to have 1 drawer component. This makes for a cleaner public API, but may complicate things internally (as the parent will have to pass down the drawer type). 

e.g. Using it would be something like:
```jsx
<Drawer type="temporary">
  <Drawer.Header className="mdc-theme--primary-bg">
    ...
  </Drawer.Header>
  <Drawer.Content>
            ...
  </Drawer.Content>
</Drawer>
```

I'll investigate and try to implement a prototype, but let me know your thoughts.

**Comment by prateekbh** [comment]
This might have similarity now, but any change from `mdc-web` would make it really tough to keep this going. Hence keeping it the way it is now would be the best approach
