### ISSUE TITLE
Declaration of IconToggle's disabled state

### ISSUE THREAD

**Issue by fantasia949** [prateekbh/preact-material-components#206]
It seems `<IconToggle>` cannot be in disabled state at initial phase
Neither of these ways works
```jsx
<IconToggle disabled>thumb_up</IconToggle>
<IconToggle className="mdc-icon-toggle--disabled">thumb_up</IconToggle>
```

**Comment by prateekbh** [comment]
try this 👇 
```
<IconToggle ref={(control)=>this.toggle = control}>thumb_up</IconToggle>
.
.
.
this.toggle.MDComponent.setDisabled(true);
```

**Comment by prateekbh** [comment]
so we delegate only events and possible class name mutations to props.
If you think this can/should be handled in class name, `mdc-web` is the right place to open the bug.
