### ISSUE TITLE
Drawer and Toolbar not working

### ISSUE THREAD

**Issue by bangive** [prateekbh/preact-material-components#211]
I setup the drawer and toolbar follow tutorial here https://prateekbh.github.io/preact-material-components
It's not working for me like this screenshot

![drawer-error](https://user-images.githubusercontent.com/11285347/29058189-43f4d620-7c39-11e7-8caf-86e72ff7f519.png)

**Comment by prateekbh** [comment]
is it about the icons?
also have u added the stylesheet for the icons?

**Comment by bangive** [comment]
i click on the text menu but it does not show drawer, the icon is not working as screenshot

**Comment by bangive** [comment]
it seem drawer button is hidden

**Comment by prateekbh** [comment]
is it live anywhere?

**Comment by prateekbh** [comment]
or just code anywhere?

**Comment by bangive** [comment]
i will upload it to firebaseapp now

**Comment by bangive** [comment]
you can access it online here https://1802d6f4.ngrok.io

**Comment by prateekbh** [comment]
<img width="671" alt="screen shot 2017-08-08 at 12 01 03 pm" src="https://user-images.githubusercontent.com/5960497/29059052-4de82676-7c31-11e7-8bfb-f591084b5f32.png">

**Comment by bangive** [comment]
So what does error say. I don't know whats the problem

**Comment by prateekbh** [comment]
I guess you haven't transpiled your code to some es5 or a lower lever es6

**Comment by bangive** [comment]
so what to do now

**Comment by prateekbh** [comment]
are you using webpack/gulp or anything?

**Comment by prateekbh** [comment]
or are you using `preact-cli`?

**Comment by bangive** [comment]
i use preact-cli

**Comment by prateekbh** [comment]
run ```preact build```

and then redeploy the `public` folder

**Comment by bangive** [comment]
you can access it now

**Comment by prateekbh** [comment]
a. add this in head 
```
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

b. can you show me the code for this screen

**Comment by bangive** [comment]
this is Header component
```
import { h, Component } from 'preact';
//import { Link } from 'preact-router/match';
//import style from './style';
import Drawer from 'preact-material-components/Drawer';
import List from 'preact-material-components/List';
import 'preact-material-components/Drawer/style.css';
import 'preact-material-components/List/style.css';
import Toolbar from 'preact-material-components/Toolbar';
import 'preact-material-components/Toolbar/style.css';


export default class Header extends Component {
	render() {
		return (
			<header>
				<Toolbar className="toolbar">
					<Toolbar.Row>
						<Toolbar.Section align-start>
							<Toolbar.Icon menu>menu</Toolbar.Icon>
							<Toolbar.Title>
								My App
							</Toolbar.Title>
						</Toolbar.Section>
						<Toolbar.Section align-end>
							<Toolbar.Icon>more_vert</Toolbar.Icon>
						</Toolbar.Section>
					</Toolbar.Row>
				</Toolbar>
				<Drawer.TemporaryDrawer ref={drawer => { this.drawer = drawer; }} >
					<Drawer.TemporaryDrawerHeader className="mdc-theme--primary-bg">
						Components
					</Drawer.TemporaryDrawerHeader>
					<Drawer.TemporaryDrawerContent>
						<List>
							<List.LinkItem>
								<List.ItemIcon>home</List.ItemIcon>
								Home
							</List.LinkItem>
						</List>
					</Drawer.TemporaryDrawerContent>
				</Drawer.TemporaryDrawer>
			</header>
		);
	}
}
```

**Comment by prateekbh** [comment]
oh yeah, this just build the UI of the toolbar, you'll need to add code to open/close,
check this
https://github.com/prateekbh/preact-material-components/blob/gh-pages/src/Components/Home/Home.jsx#L81

**Comment by bangive** [comment]
i am checking it

**Comment by bangive** [comment]
thank you for your help

**Comment by DarinLevesque** [comment]
Could you post the link above again please? https://github.com/prateekbh/preact-material-components/blob/gh-pages/src/Components/Home/Home.jsx#L81 is broken.

**Comment by prateekbh** [comment]
https://github.com/prateekbh/preact-material-components/blob/master/docs/src/components/app/index.js#L211
