### ISSUE TITLE
Missing css class when build

### ISSUE THREAD

**Issue by bangive** [prateekbh/preact-material-components#213]
Run fine when use command preact watch. But when use preact build it miss the class ```"mdc-temporary-drawer mdc-typography"``` and ```"material-icons mdc-toolbar__icon--menu"```. So for the UI to work, i must add thoes class manually like this:
```
<Toolbar>
  <Toolbar.Row>
    <Toolbar.Section align-start>
      <Toolbar.Icon className="material-icons mdc-toolbar__icon--menu" menu href="#" onClick={this.openDrawer}>menu</Toolbar.Icon>
	<Toolbar.Title>
	  Joider
       </Toolbar.Title>
       </Toolbar.Section>
 </Toolbar.Row>
</Toolbar>
<Drawer.TemporaryDrawer className="mdc-temporary-drawer mdc-typography" ref={drawer => { this.drawer = drawer; }} >
  <Drawer.TemporaryDrawerContent>
    <List>
     <List.LinkItem>
	<List.ItemIcon>home</List.ItemIcon>
          Home
	</List.LinkItem>
    </List>
  </Drawer.TemporaryDrawerContent>
</Drawer.TemporaryDrawer>
```

**Comment by filoozom** [comment]
Confirmed, ```mdc-${componentName}``` is never added when using ```npm run build```.

**Comment by prateekbh** [comment]
Is this only for this components?

**Comment by filoozom** [comment]
It's for every component as far as I can tell, but the HTML actually includes the classes. I guess they're just somehow removed with JS after. It works when using ```element.attributes.className = this.getClassName(element);``` instead of ```element.attributes.class = this.getClassName(element);``` in ```MaterialComponent.js```.

Any reason why ```class``` was used instead of ```className``` there? Also, what is this line for; ```const autoInits = this.getAutoInitNames();```? ```autoInits``` isn't even used.

I have a PR ready if you can confirm that we can use ```className``` instead of ```class```, but I still haven't found why those classes disappear.

**Comment by prateekbh** [comment]
>Any reason why class was used instead of className there? Also, what is this line for; const autoInits = this.getAutoInitNames();? autoInits isn't even used.

since it was attributes of element hence class was used, but I guess preact does something on top of it. so its ok.

autoInit class name how I tried doing it initially and then dropped the approach
