### ISSUE TITLE
Layout Grid changed upstream (for info)

### ISSUE THREAD

**Issue by IrregularShed** [prateekbh/preact-material-components#214]
I've noticed that the Layout Grid in Material Components has changed. Previously it always gave 12 columns regardless of the screen size but now it's 12 in desktop, 8 in tablet and 4 in phone sizes.

When I get a chance I'll revisit the Layout Grid component and its documentation to bring this into step. Right now I've got a client breathing down my neck, an injured wife and a bored son so it may take a while for me to manage this!

**Comment by prateekbh** [comment]
Hope things get better for you soon... I'll try to fix this soon

**Comment by prateekbh** [comment]
can you point me to some more details, i am unable to find this change in the change log

**Comment by IrregularShed** [comment]
Hi - back on this now!

I can't find the exact point where it changed myself - I installed my project on a new server and found the layout had broken completely. Working through the versions of preact-material-components in my package.json, I found forcing it to 1.0.7 worked - later versions had problems with the grid. (I'm working from memory and the year I've had is making it all a bit foggy!)

I'll modify the component over the next couple of days and bring it back into line.

**Comment by IrregularShed** [comment]
OK, it turns out that the problem I was having with the grid was down to the introduction of the LayoutGrid.Inner (which had completely passed me by - 2017 has been like that). The number of columns were unrelated (and I think may just have been me making a mistake way back at the beginning, when I was moving from MDL to this).

I've modified the documentation to correct things a little. I'd also fixed the SCSS file to show the alignment properly, but you got in there first!
