### ISSUE TITLE
Toolbar: cannot get instance of MDComponent

### ISSUE THREAD

**Issue by fantasia949** [prateekbh/preact-material-components#218]
``` jsx
<Toolbar ref={tb => this.tb = tb}>
          <Toolbar.Row>...</Toolbar.Row>
</Toolbar>
```

``` js
console.log(this.tb.MDComponent) // undefined
```
I need that instance to handle 'MDCToolbar:change' event. But it's always undefined. Do I miss something?

**Comment by prateekbh** [comment]
is `this.tb` to the right object?

**Comment by prateekbh** [comment]
so it seems like we have enabled the jS object for `Toolbar` yet, we'll add this and release a new version ASAP.

**Comment by filoozom** [comment]
```1.1.4``` was just published, and you can use ```this.tb.MDComponent``` or even easier ```onChange``` on the ```Toolbar```:
```js
<Toolbar onChange={this._onChange}>
    <Toolbar.Row>...</Toolbar.Row>
</Toolbar>
```
