### ISSUE TITLE
Fix gh-pages on IE 11

### ISSUE THREAD

**Issue by filoozom** [prateekbh/preact-material-components#220]
The documentation does not work on IE 11 because of a ```babel``` / ```webpack``` configuration issue.

Maybe we should move ```gh-pages``` to ```preact-cli```?

**Comment by prateekbh** [comment]
do we need someone to help us on this?
if yes plz @ reznord

**Comment by filoozom** [comment]
Well, I'd like to port it to ```preact-cli``` so that we'd only have to run ```preact build``` and "serve" the ```dist``` folder (is that even possible with ```gh-pages```? Will have to try). I think it would make everything a little bit easier as we wouldn't have to bother with ```webpack``` / ```babel``` again. Also, ```preact-cli``` can prerender all our pages which would also be useful.

**Comment by prateekbh** [comment]
@filoozom closing this, as we migrated to `preact-cli`. I hope this has fixed it
