### ISSUE TITLE
Textfield layout breaks when no value

### ISSUE THREAD

**Issue by gpoitch** [prateekbh/preact-material-components#236]
If you have a Textfield and delete it's value, the layout can become broken:

![textfield](https://user-images.githubusercontent.com/411908/29974707-ce5ea842-8f01-11e7-8bd1-980eb599d942.gif)

It looks like because it only has this class when there is a value: https://github.com/prateekbh/preact-material-components/blob/master/Textfield/Textfield.jsx#L73-L75

This can occur when your Textfield is connected to state, e.g,:
```jsx
<Textfield value={ this.state.lastName } onInput={ e => this.setState({ lastName: e.target.value }) } />
```

**Comment by filoozom** [comment]
Tried the same code as you on latest ```preact-material-components``` version, and it doesn't quite result in the same as your gif. In my case I still have a label when I remove the last character, but it doesn't slide down as expected. It just "teleports" from the floating position to the "placeholder" position.

Do you have a specific use case for this? One easy way to solve this would be to use uncontrolled components like this:
```html
<Textfield defaultValue={this.state.lastName} onInput={e => this.setState({ lastName: e.target.value })} />
```

Actually, this won't work because we can't get a ```ref``` on the underlying ```TextfieldInput```,  but I can fix that.

I think we might also be able to fix the issue I'm having by adding an "or is focused" condition in the if you mentioned, but can't reproduce your gif.

**Comment by gpoitch** [comment]
Here's a minimal reproduction (also exhibits some other buggy behavior):
http://jsfiddle.net/emvg1ua8/

Preact doesn't have defaultValue, and what I'm doing is pretty common usage.  Should be fixable by using focus instead of presence of value to determine the label state.  I will try to submit a PR.

**Comment by filoozom** [comment]
I know that it's common, was just suggesting a temporary fix. I think that #237 solves at least a few problems. Still don't get quite the same result as you on JSFiddle though. The label goes back on the input as a placeholder when I remove the last character. Maybe has something to do with different browsers?
Regarding the ```placeholder``` issue, I guess we should just remove it on JS-enabled clients and keep it only for degraded inputs.

**Comment by gpoitch** [comment]
@filoozom thank you for the quick feedback and your temp fix suggestion. Your PR looks like a promising fix.

My fiddle looks like it uncovered some other issues not related to this. (why doesn't the label have a class initially?).  Maybe it's something to do with using the umd build?

**Comment by filoozom** [comment]
Added ```mdc-textfield__label``` to the label in my last commit, guess I just forgot it when working on ```Textfield``` last time.

Also, I'm not sure if ```material-components-web``` is really compatible with libraries that re-render the whole element every time a prop or the state changes. Now we're actually just trying to rewrite the whole ```MDCTextfield``` in our component to make it work as it should, for example the ```onFocus``` method should be handled by ```MDCTextfield``` I think. But let's see if this works out.

**Comment by prateekbh** [comment]
Quick check what's the difference between the demo page and your gif?
https://prateekbh.github.io/preact-material-components/#/component/textfield

**Comment by gpoitch** [comment]
> Quick check what's the difference between the demo page and your gif?

Just connecting its `value` to state.

**Comment by filoozom** [comment]
Right, in the demo there is state but never ```value={this.state.someValue}```, which makes it an uncontrolled component. I guess that we should rewrite the whole ```material-components-web``` in ```preact``` to make it 100% compatible and not calculating / rendering things twice.

**Comment by gpoitch** [comment]
@filoozom check this out - I rewrote the component simply and it seems to work pretty well: http://jsfiddle.net/emvg1ua8/1/

**Comment by filoozom** [comment]
Looks nice, will have a closer look tomorrow. My latest commit on #237 should work too though, and of course our component also includes ```helptext``` and ```multiline``` :-)

**Comment by gpoitch** [comment]
Indeed, i didn't add all the features yet 😀, but showing that you may not have to track floating and focus state since it looks like material-components-web is handling that.

**Comment by filoozom** [comment]
Yes, thanks for the information, it's really interesting! It might just be thanks to the missing class on the ```label```, or maybe it's because we re-render a child of the ```Textfield``` (```TextfieldInput```) which could be a problem for ```MDTextfield```, I'll run some tests 😃.

**Comment by filoozom** [comment]
Oh yeah, and we track the floating label to avoid FOUC 😉. We might need to monitor focus as well for the same reason because inputs can also be focused before JS kicks on with ```autofocus```.

**Comment by prateekbh** [comment]
i'll do some quick experiments with this today and come back on it

**Comment by prateekbh** [comment]
ok so the problem in hand(layout breakage) is caused by this line:
https://github.com/prateekbh/preact-material-components/blob/master/Textfield/Textfield.jsx#L73

I guess a simple change to `'value' in props` should change the problem in hand.
