### ISSUE TITLE
Add support for GridList

### ISSUE THREAD

**Issue by edhille** [prateekbh/preact-material-components#239]
I'm working on a small project and have leveraged `preact-material-components`, but I noticed it's missing support for `GridList`. I've started to implement this in the project and can submit a PR, but wanted to understand how strictly you try to adhere to the [MDC Design & API documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-grid-list) as well as maintaining compatibility with the [Material-UI API](http://www.material-ui.com/#/components/grid-list) (interestingly enough, I notice that neither of the two aforementioned projects are 100% in sync with each other.

Please let me know how you prefer contributions to be designed and I will work to match up with your approach.

Another component that I would also consider in this camp would be the (IconButton)[http://www.material-ui.com/#/components/icon-button], though that would be a follow-on PR.

**Comment by prateekbh** [comment]
hi @edhille,
Thanks for taking this up, if you'd explore `preact-material-components` you'll see that its a minimal wrapper over `mdc-web`. The way currently all components are implemented you just need to put their listed states in an array and name in a constant, and a lot of stuff would be taken care of for you.
we do not really go around implementing anything not implemented in the mdc-web. If you need any new component, you should go ahead and raise and issue in `mdc-web`.

But the `grid-list` looks like something which seemed to be missing in our catalog, please feel free and raise a PR for the same, do take a look on how other components are implemented.
