### ISSUE TITLE
Material specific props not being removed before render

### ISSUE THREAD

**Issue by gpoitch** [prateekbh/preact-material-components#240]
Internal mdc props are being set on raw DOM elements (e.g. ripple, label, helptext, etc).  Although this doesn't cause any bugs at the moment, these are not valid html attributes and have some overhead of having to be set.

From the demo site:
![screen shot 2017-09-05 at 11 27 09 am](https://user-images.githubusercontent.com/411908/30069624-3dfe0f6e-922f-11e7-84f7-c01116ad7cb6.png)

This code is supposed to account for it:
https://github.com/prateekbh/preact-material-components/blob/2ac3e39de474f028cf3fc76feebcd40af3bfe6c2/MaterialComponent.js#L65-L67

However, I think this should happen before `this.materialDom(this.props)` is called.

**Comment by filoozom** [comment]
Oh, actually this code just removes mdcProps, not custom attributes we add to the components. Misunderstood what you meant on the other PR, guess we should indeed fix this. Should be able to add an array to every components and remove all contained attributes in ```MaterialComponent.js```. Or deconstruct every prop in ```materialDom```, might be better. What do you think @prateekbh?

**Comment by prateekbh** [comment]
`MaterialComponent.js` seems to be the best place to do this
