### ISSUE TITLE
Enforce code style

### ISSUE THREAD

**Issue by filoozom** [prateekbh/preact-material-components#243]
We should enforce a given code style and improve linting for the source code. For now, a lot of PRs contain lines that don't change in the slightest except their formatting, which makes it more difficult to track changes and review pull requests.

Also, I think that the current code doesn't respect all ```eslint``` rules. At least VS Code shows errors, I'll have to check if they're indeed from our eslint config.

**Comment by prateekbh** [comment]
hmmm we need to get the current code and prettier in sync, I want to keep manual linting to minimum

**Comment by filoozom** [comment]
Not quite sure why the output of the prettier isn't the same for your PR and mine just before that. Maybe it didn't work for me? Could this be an issue with different operating systems?

Should at least get ```prettier``` and ```eslint``` in sync though, so that we don't get those pesky linting warnings.

**Comment by filoozom** [comment]
This seems like a good start: https://github.com/prettier/prettier/blob/master/README.md#eslint!

Will check it tomorrow.
