### ISSUE TITLE
Tabs component with preact-router links

### ISSUE THREAD

**Issue by filoxo** [prateekbh/preact-material-components#257]
It seems that the Tab component renders its own `a` element which is incompatible with [preact-router](https://github.com/developit/preact-router)'s `Link` element. Is there a way to expose or defer the anchor to a child of the tab component? 

#### Attempt: Link wrapping Tab 

```
<Link to="/A">
   <Tabs.Tab>A</Tabs.Tab>
</Link>
```

If the Tab is wrapped in a Link, the Tab moves the indicator correctly but the URL does not change nor is the correct route rendered.

#### Attempt: Tab with Link child

```
<Tabs.Tab>
  <Link to="/A"></Link>
</Tabs.Tab>
```

This does nothing as far as I can tell.

#### Workaround 

I've worked around this like so:

```
import { Router, route } from 'preact-router'

import Tabs from 'preact-material-components/Tabs'
import 'preact-material-components/Tabs/style.css'

export default class SomeApp extends Component {
  routeTo = (e, to) => {
    e.preventDefault()
    route(to)
  } 
  render() {
    return (
      <div>
        <Tabs indicator-accent={true}>
          <Tabs.Tab href="/A" onClick={(e) => { routeTo(e, '/A') }}>A</Tabs.Tab>
          <Tabs.Tab href="/B" onClick={(e) => { routeTo(e, '/B') }}>B</Tabs.Tab>
          <Tabs.Tab href="/C" onClick={(e) => { routeTo(e, '/C') }}>C</Tabs.Tab>
        </Tabs>
        <Router>
          <div path="/A">A</div>
          <div path="/B">B</div>
          <div path="/C">C</div>
        </Router>
      </div>
    )
  }
}
```
This way the rendered Tabs anchor still has the `href` attribute but its actually routing using preact-router. Of course, some sort of HoC could do the same above in a more elegant way but it would be much better to have the Tab component integrate with client-side router linking.

**Comment by filoozom** [comment]
Please refer to #177 and let me know if your use-case is different from that one.

**Comment by filoxo** [comment]
WHOA... well, after tinkering with all of this, and spent the time writing this issue up, everything is working as expected... Seems like the issue I was experiencing may have been because of a lack of a route definition. This works just fine now:

```
<Tabs indicator-accent={true}>
    <Tabs.Tab href="/daily">Daily</Tabs.Tab>
    <Tabs.Tab href="/weekly">Weekly</Tabs.Tab>
    <Tabs.Tab href="/monthly">Monthly</Tabs.Tab>
</Tabs>
<Router onChange={this.handleRoute}>
    <div path="/daily">daily</div>
    <div path="/weekly">weekly</div>
    <div path="/monthly">monthly</div>
</Router>
```
