### ISSUE TITLE
Sample code for every demo

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#264]
It'll be better to have snippet of code below every demo section.
This'll help users to easily configure their code better

**Comment by keemor** [comment]
I was testing demo for Drawer https://www.webpackbin.com/bins/-Kv1t9u-xQemYASknB1o 
All the components are built without errors but I cannot see it, what is missing there?

**Comment by prateekbh** [comment]
nothing! this has built the drawer, now put a button or something 
and then call
```
this.drawer.open();
```

**Comment by keemor** [comment]
The following code results: _TypeError: this.drawer.open is not a function_

https://www.webpackbin.com/bins/-Kv1t9u-xQemYASknB1o

```
export default class DrawerPage extends Component {
   constructor(props) {
        super(props);
        this.handleToggle = this.handleToggle.bind(this);
    }

    handleToggle() {
        this.drawer.open();
    }

    render() {
        return (
            <div>
                <Button onClick={this.handleToggle}>Toggle</Button>
                <Drawer.TemporaryDrawer
                    ref={drawer => {
                        this.drawer = drawer;
                    }}>
                    <Drawer.TemporaryDrawerHeader className="mdc-theme--primary-bg">
                        Components
                    </Drawer.TemporaryDrawerHeader>
                    <Drawer.TemporaryDrawerContent>
                        <List>
                            <List.LinkItem>
                                <List.ItemIcon>home</List.ItemIcon>
                                Home
                            </List.LinkItem>
                        </List>
                    </Drawer.TemporaryDrawerContent>
                </Drawer.TemporaryDrawer>
            </div>
        );
    }
}
```

I was also looking on the example here: http://www.material-ui.com/#/components/drawer
Which implements toggling of drawer via state.

**Comment by prateekbh** [comment]
a.) this should work ```this.drawer.MDComponent.open = true```
b.) `drawer.open` was just  proxy function, which we can implement as a state too

**Comment by mellogarrett** [comment]
Which components need examples added? I can help with this

**Comment by prateekbh** [comment]
ummm pretty much all... the samples which are there on demo needs code sample below them

**Comment by keemor** [comment]
There could be expandable element with code inside like in http://www.material-ui.com/#/components/card
So there would be less scrolling on pages with many demos

**Comment by wuweiweiwu** [comment]
@prateekbh I would like to take some of them :)

**Comment by prateekbh** [comment]
yes please feel free to comment which one you are starting with and send PRs right away @wuweiweiwu :)

**Comment by wuweiweiwu** [comment]
Ill take `TextField` for now and add more :)

**Comment by prateekbh** [comment]
much needed thanks 👍

**Comment by wuweiweiwu** [comment]
Just finished `textfield`

Ill take on:

- [ ] linear progress
- [ ] switch
- [ ] menu
- [ ] tabs
- [ ] dialog

Ill keep this list updated :)
