### ISSUE TITLE
select date demo

### ISSUE THREAD

**Issue by redimongo** [prateekbh/preact-material-components#271]
I am wondering if you have a date select demo? As having a text field that users put in their date of birth may result in the following types of dates being entered.

- 02/03/2011
- 02-03-2011
- 03-02-2011
- 03-02-11
- 03/02/11
- 2nd of march 2011

I think people can see my point here.

Would be great to have a MDC looking date selector.

**Comment by prateekbh** [comment]
i didn't really get you.
do you need a text field+ date selector demo? or text field which re adjust text according to a specified format or what?

**Comment by redimongo** [comment]
ideally something that looks like this https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B3321sZLoP_Hamc5d1k2SmhlV2c/components-pickers-date3.png

**Comment by prateekbh** [comment]
ahh ok, the problem with this is, PMC is maintained as a wrapper over `mdc-web`. So a new component request should actually go to `mdc-web` and we'll expose it the preact way.
