### ISSUE TITLE
Primary & Secondary buttons fail to get proper colors

### ISSUE THREAD

**Issue by keemor** [prateekbh/preact-material-components#278]
Hi,

In PMC 1.2.0 secondary & primary button do not get proper blue and red colors:

https://www.webpackbin.com/bins/-Kv1t9u-xQemYASknB1o

Also examples in the documentation are broken:
https://material.preactjs.com/component/button

Another thing is that I can't find how to apply dark theme to the elements.
I tried:
```
<html class="mdc-theme--dark"></html>
<body class="mdc-theme--dark"></body>
<section class="mdc-theme--dark"></section>
```

Thanks for your effort!

**Comment by prateekbh** [comment]
@keemor sry, `mdc-web` took away primary and secondary.
try refreshing https://material.preactjs.com/component/button, should work.
now primary and secondary is supported as classes as shown in the page above

**Comment by keemor** [comment]
@prateekbh I don't see any changes yet

**Comment by prateekbh** [comment]
<Button raised className="mdc-theme--primary-bg">Primary Raised button{" "}</Button>

<Button raised className="mdc-theme--secondary-bg">Primary Raised button{" "}</Button>

**Comment by keemor** [comment]
https://www.webpackbin.com/bins/-Kv1t9u-xQemYASknB1o

**Comment by keemor** [comment]
Ok, works on localhost

**Comment by keemor** [comment]
Looks like there's another version of docs https://preact-material-components.surge.sh/component/button

**Comment by prateekbh** [comment]
heh sorry need to bring that down

**Comment by prateekbh** [comment]
@filoozom i guess `preact-material-components.surge.sh` is from your account. can you please teardown this?

**Comment by keemor** [comment]
It worked on localhost because of Theme/style.css imported by chance

Here it works as well: https://www.webpackbin.com/bins/-Kv1t9u-xQemYASknB1o

I'm not sure how I can help you with PR

**Comment by prateekbh** [comment]
you just need to add the theme import statement here
https://github.com/prateekbh/preact-material-components/blob/master/docs/src/routes/button/sample.txt

**Comment by filoozom** [comment]
@prateekbh Done!
