### ISSUE TITLE
Add TypeScript declaration file

### ISSUE THREAD

**Issue by YePpHa** [prateekbh/preact-material-components#280]
This will make it possible to use this library in TypeScript projects.

**Comment by prateekbh** [comment]
i'll try to look at this, but i have like 0 experience in this so might take long

**Comment by YePpHa** [comment]
Okay, I might consider making a PR then.

**Comment by prateekbh** [comment]
awesome and welcome 👍

**Comment by cvuorinen** [comment]
Any progress on this yet? I'm interested in using this project with TypeScript as well, and I could help with the typings.

**Comment by prateekbh** [comment]
nothing started as of now, feel free to begin a PR.
@YePpHa have u started any work already?

**Comment by YePpHa** [comment]
Yes, I've started some work on this, but it's not completed yet. I've written about 50% of declaration files for the components. However, one thing that I haven't started on yet is creating a declaration for the `MDComponent` property that some of the components have.

Progress is here: https://github.com/YePpHa/preact-material-components/tree/typescript-declaration

**Comment by cvuorinen** [comment]
Great, looking good. I'll try them out later when I have time, but one question. Is there a reason for declaring inherited methods like `componentDidMount` and `materialDom` on each component? Seems to me like those should be redundant since they are already inherited.

**Comment by YePpHa** [comment]
You're right. Private methods are just redundant.

The reason I added the `componentDidMount` and `materialDom` is because they override the method from the class they extend from and therefore they're not the method that was declared in `MaterialComponent.d.ts`. Though, I'm not sure if it actually does any difference, but I've added them for technicalities.

**Comment by cvuorinen** [comment]
If the overriding method does not change the method signature I think they are redundant from the type declaration point of view. The declared type will have the same method either way.

**Comment by porfirioribeiro** [comment]
I'm also using this library with typescript, i will try to help with this also
