### ISSUE TITLE
Incorrect rendering with snackbar box-sizing

### ISSUE THREAD

**Issue by eligao** [prateekbh/preact-material-components#316]
Hi,

When using the snackbar, I notice it assumes the user using `box-sizing: content-box`.
However in the case when `box-sizing: border-box`  is set globally (which happens very often), the body of snackbars are not filling the width of the screen on small devices.

I've created a simple sample 
[HERE](https://codesandbox.io/s/7w20pml681)

When the page is opened on a mobile phone, the problem occurs.
Adding the following css can help address the problem, but it doesn't seem elegant.
Is it possible to solve it more gracefully?

```css
.mdc-snackbar {
  box-sizing: content-box;
}

```

**Comment by prateekbh** [comment]
yep verified. This indeed is a bug. However you'll need to open a bug here:
https://github.com/material-components/material-components-web/issues

as this is the parent repo and we don't do any alterations in the css. also please refer this bug there or the parent bug here. 
Thanks 👍

**Comment by eligao** [comment]
I've submitted an issue in the parent repo at https://github.com/material-components/material-components-web/issues/1440

**Comment by prateekbh** [comment]
Thank you so much :)

**Comment by eligao** [comment]
It seems the issue is resolved in the parent repo via https://github.com/material-components/material-components-web/pull/1453

**Comment by prateekbh** [comment]
awesome, this will get fixed in next publish then
