### ISSUE TITLE
Select width

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#318]
`div.mdc-select` seems to have a static width of only 9px for some reason. For this reason, it does not show the currently selected value (or the hintText).

I can inspect the element and set the width higher and see the span correctly, but when I interact the the dropdown it sets it back to 9px.

<img width="850" alt="screen shot 2017-10-20 at 2 03 39 pm" src="https://user-images.githubusercontent.com/9908831/31835437-87499344-b59f-11e7-89e3-f9805339c148.png">

**Comment by prateekbh** [comment]
are there no members in this select box?
or is there no selected value at the beginning?

i see a similar case working fine here: https://material.preactjs.com/component/select

**Comment by mellogarrett** [comment]
There are 3 members, initial `selectedIndex` is set to -1

**Comment by prateekbh** [comment]
can you share your jsx code?

**Comment by mellogarrett** [comment]
Sure, here it is: 

```
import { h, Component } from "preact";

import Select from "preact-material-components/Select";

export default props => {
  const { question, onChange, i } = props;
  const selectedIndex = question.get("selectedIndex");
  const selectOptions = question.get("options");
  const selectedValue = selectOptions[selectedIndex] || null;

  const optionElements = selectOptions.map(o => <Select.Item>{o}</Select.Item>);

  return (
    <div>
      <Select
        hintText={selectedValue ? selectedValue : "Select an option"}
        selectedIndex={selectedIndex}
        onChange={onChange.bind(undefined, i)}
      >
        {optionElements}
      </Select>
    </div>
  );
};
```

I am importing the css globally

**Comment by prateekbh** [comment]
so here are two things:
a.) looks like you cannot instantiate an empty `Select` and that might be the case since you are passing it through props, please check. I'll also try asking this to `mdc-web` team
b.) for the width, I guess you can specify the `min-width` or a fixed width.

**Comment by mellogarrett** [comment]
It seems like `selectedIndex` coming from props _was_ causing an issue. Once I changed that from an Immutable.js structure to a plain JS object & added `style={{ minWidth: '100px' }}` to the `Select` element, everything is working as expected.

Thanks a ton @prateekbh !!
