### ISSUE TITLE
How to use linear-progress with determinate state?

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#322]
I tried just passing `progress` as a number between [0, 1], as the [MDC docs](https://material.io/components/web/catalog/linear-progress/) say to do, but it always renders the progress bar completely full

JSX:
```
<LinearProgress progress="0.5" />
```

**Comment by prateekbh** [comment]
<LinearProgress ref={pbar=>{this.pbar=pbar}} />

this.pbar.MDComponent. setProgress(0.5)

**Comment by prateekbh** [comment]
but yeah, probably we should make this a prop

**Comment by mellogarrett** [comment]
This code: 
```
componentDidMount = () => {
    console.log(this.pbar);
    this.pbar.MDComponent.setProgress(".2");
};
```
results in this: 

<img width="652" alt="screen shot 2017-10-23 at 11 52 49 am" src="https://user-images.githubusercontent.com/9908831/31899092-bca3096c-b7e8-11e7-85bc-078c208c563c.png">

**Comment by prateekbh** [comment]
my bad its
```
this.pbar.MDComponent.progress=0.5
```

which also makes it way easier to be implemented as a prop

**Comment by mellogarrett** [comment]
Awesome! 

I think progress is defaulting to `1` as well, which on initial load causes an animation from full bar down to whatever your desired initial progress is. 

Maybe set this initial progress to `0` instead?

**Comment by prateekbh** [comment]
not really sure if initial progress falls under PMC or mdc-web

**Comment by mellogarrett** [comment]
Are there any plans to make `progress` a prop?

**Comment by prateekbh** [comment]
it is there... sorry the doc says its values are `true/false` but actually its from 0 to 1

`progress={0..1}`
