### ISSUE TITLE
Slider discrete

### ISSUE THREAD

**Issue by porfirioribeiro** [prateekbh/preact-material-components#324]
Would it be possible to add the discrete option?

https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider#discrete-slider

**Comment by filoozom** [comment]
Hey, sure!
If you're willing to open a PR, it's as simple as adding 'discrete' to `_mdcProps`.

The line you'd be interested in is: https://github.com/prateekbh/preact-material-components/blob/cabaffeb4bc2828723e86a13ffa6d316af70d767/Slider/Slider.jsx#L12

**Comment by prateekbh** [comment]
oh yes ofcourse, we just need to add an option here
https://github.com/prateekbh/preact-material-components/blob/master/Slider/Slider.jsx#L12

and a conditional dom before this:
https://github.com/prateekbh/preact-material-components/blob/master/Slider/Slider.jsx#L69

let me know if you wanna do a PR or else I can do this tomorrow

**Comment by porfirioribeiro** [comment]
I'm still exploring the code base to understand how to do it.
It also needs to render a different DOM or just some part's?

**Comment by prateekbh** [comment]
just an additional pin dom

**Comment by porfirioribeiro** [comment]
Well, i think it's done.

Hope it's ok with your guidelines

**Comment by prateekbh** [comment]
its perfect, just a small change required
