### ISSUE TITLE
Textfield does not implement `valid` prop

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#332]
I'm trying to pass a prop `valid` to `<Textfield />`, as described [here](https://material.io/components/web/catalog/input-controls/text-fields/#mdctextfield-api)

Doesn't seem to do anything. 

I would expect it to add the appropriate classes, for example `.mdc-textfield--invalid` to the top level div.

**Comment by prateekbh** [comment]
Interesting! so you want to initialize your textfield with `valid={false}`?
so far its more of internally managed thing, hence we never exposed it on top level surface, but yeah can be done easily as like in slider/menu/checkbox etc

**Comment by mellogarrett** [comment]
<img width="709" alt="screen shot 2017-10-26 at 4 05 57 pm" src="https://user-images.githubusercontent.com/9908831/32074496-9860c4d2-ba67-11e7-8d44-48a31566a0ab.png">

Basically, if the user clicks `NEXT` I want to change the TextField `valid` prop from `true` to `false`, which will highlight the field and draw attention to the user that they need to input a value for the required field.

I'm already using the same logic to determine what `NEXT` actually does (whether it moves on or does nothing).

**Comment by prateekbh** [comment]
@mellogarrett isn't `required` not helping? or are you looking for regexp or custom logic?

**Comment by mellogarrett** [comment]
`required` requires that you focus, then un-focus the TextField to trigger the red styling as seen here: 

<img width="227" alt="screen shot 2017-10-26 at 4 11 58 pm" src="https://user-images.githubusercontent.com/9908831/32074820-8f478830-ba68-11e7-8295-0c7a242a5483.png">

I basically want to duplicate this functionality of highlighting the element, but on click of `NEXT` (if there is no value present).

**Comment by prateekbh** [comment]
sure, understood and taken as a valid bug.

till then you can create a ref to this textfield and set ref.MDComponent.valid=false

**Comment by mellogarrett** [comment]
I'll take this, I just might need some direction on getting started.

**Comment by prateekbh** [comment]
@mellogarrett take a look at this:
https://github.com/prateekbh/preact-material-components/blob/master/Menu/Menu.jsx#L58-L60
