### ISSUE TITLE
Data Table

### ISSUE THREAD

**Issue by ashishWaghmare** [prateekbh/preact-material-components#335]
In sample can we have example of Data Table
https://material.io/guidelines/components/data-tables.html#data-tables-interaction

**Comment by prateekbh** [comment]
sample basically have a samples for all the components, so not sure if we would want a data table here.

@filoozom @mellogarrett @YePpHa thoughts?

**Comment by YePpHa** [comment]
[material-components-web#57](https://github.com/material-components/material-components-web/issues/57) hasn't implemented that component yet. We should wait for them to implement it before we do anything.

**Comment by prateekbh** [comment]
oh nice... thanks for digging this up @YePpHa.

I'll close this for now, we'll take this up when they implement the underlying component
