### ISSUE TITLE
Label's position is not correct in multiline-mode TextField

### ISSUE THREAD

**Issue by fantasia949** [prateekbh/preact-material-components#365]
Please see the screenshot

![image](https://user-images.githubusercontent.com/1866854/32206554-651dd488-be28-11e7-8d13-9978b929eb1d.png)

The label is always anchored at bottom while in the original  material-components-web, the label is anchored at top.

**Comment by MobiusHorizons** [comment]
I can confirm this is not working correctly. You can see the issue in the example page https://material.preactjs.com/component/textfield if you just expand the textfield. I'm also seeing that it does not expand the textarea height when you expand the number of rows, which may or may not be a related bug.

**Comment by sumiet** [comment]
hey, i'd like to claim this issue, it'll be my first OSS contribution even though i've been working as a developer for years.

**Comment by prateekbh** [comment]
@sumiet awesome! go ahead its yours

**Comment by sumiet** [comment]
@prateekbh Thanks! I have made the changes in the code, but currently unable to figure out on how to check it on demo? Do I need to create a demo website using the library? Is there some other methodology to check the behavior while developing this. Please help.

**Comment by prateekbh** [comment]
there a folder `sample` thats like a rough playground... try it in thr

**Comment by sumiet** [comment]
@prateekbh I am bit delayed here. But can you help me with the commands to run the code in sample folder

**Comment by prateekbh** [comment]
@sumiet this one got covered in the last release as it was a little critical, would you mind to another beginner bug?

**Comment by sumiet** [comment]
@prateekbh sure that would be really great. Can you guide me on which should I take up. I am new to both OSS and react community. Thanks!

**Comment by prateekbh** [comment]
@sumiet here's a super easy thing
https://github.com/prateekbh/preact-material-components/issues/417
