### ISSUE TITLE
Checkbox issues

### ISSUE THREAD

**Issue by JarLowrey** [prateekbh/preact-material-components#368]
[Checkbox doc](https://material.preactjs.com/component/checkbox) says to use form field as FormField, but it's actually Formfield. This caused an [issue here](https://github.com/developit/preact-cli/issues/42#issuecomment-303342496)

Edit: Copy+pasting in the code snippets results in checkbox labels bottom aligned. Not sure why.

Edit: Also if you click the label instead of the checkbox, the pink animation does not go away until you click again. This happens on the demo pages.

**Comment by JarLowrey** [comment]
This is unrelated, but it seems like the buttons do not have a default margin. Is that expected behavior?

**Comment by prateekbh** [comment]
a.) Yes the `Formfield` should be fixed
b.) Pink animation bug is open with `mdc-web`
c.) We don't really have any call on css `mdc-web` owns it completely
c.) Can you explain `Layout Grid` with some screenshot?

**Comment by JarLowrey** [comment]
I would think it is supposed to change vertical alignment right? It doesn't seem to do anything in the examples. Thanks!

![selection_033](https://user-images.githubusercontent.com/7429786/32709454-75e6263c-c7fe-11e7-8972-87f6023a4b10.png)

**Comment by prateekbh** [comment]
Update: this bug is due to the fact we were not giving height to the row. will update the demo.
