### ISSUE TITLE
Add support for Textfield with Leading/Trailing icons

### ISSUE THREAD

**Issue by mattiagalati** [prateekbh/preact-material-components#370]
Cannot figure out how to achieve the feature "Textfield - Leading/Trailing icons" as presented here: https://material-components-web.appspot.com/textfield.html

**Comment by prateekbh** [comment]
woops this is currently un supported, happy to take this as a feature request.

**Comment by prateekbh** [comment]
@mellogarrett will you be able to take this up?

**Comment by mellogarrett** [comment]
yea, I can work on this. @mattiagalati the link is broken. Mind updating?

**Comment by prateekbh** [comment]
https://material-components-web.appspot.com/text-field.html
