### ISSUE TITLE
LayoutGrid.Cell loses Cols size classes when className is passed as prop

### ISSUE THREAD

**Issue by mattiagalati** [prateekbh/preact-material-components#401]
Hy, I've noticed that the "className" prop passed to a LayoutGrid.Cell completely override the cols size specified.

This is some test source, that behave correctly:
```jsx
return (<LayoutGrid>
      <LayoutGrid.Inner>
        {
          (modules).map((element) => {
            return (<LayoutGrid.Cell key={element.id} phoneCols="2" tabletCols="4">
              <Link to={`/app${element.path}`}>
                <span className={style.cell_tile}><img src={element.image}/></span>
                <span className={style.cell_title}>{element.title}</span>
              </Link>
            </LayoutGrid.Cell>)
          })
        }
      </LayoutGrid.Inner>
    </LayoutGrid>);
```
![image](https://user-images.githubusercontent.com/6606297/32824148-235a740c-c9e0-11e7-97f8-f3b5ac8019d4.png)
(the classes generated for the cell are "**mdc-layout-grid__cell mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-2-phone**")

Now, let's try to add a custom className to the component:
```jsx
return (<LayoutGrid>
      <LayoutGrid.Inner>
        {
          (modules).map((element) => {
            return (<LayoutGrid.Cell key={element.id} className={style.cell} phoneCols="2" tabletCols="4">
              <Link to={`/app${element.path}`}>
                <span className={style.cell_tile}><img src={element.image}/></span>
                <span className={style.cell_title}>{element.title}</span>
              </Link>
            </LayoutGrid.Cell>)
          })
        }
      </LayoutGrid.Inner>
    </LayoutGrid>);
```
when className is provided, the cell render as this:
![image](https://user-images.githubusercontent.com/6606297/32824082-d3d6db46-c9df-11e7-9b62-362267200476.png)
(this time the classes generated are only "**mdc-layout-grid__cell**" and my custome class)

**Comment by porfirioribeiro** [comment]
Was coming here exactly to report the same error!
The classes we pass should be added to the classname and not override it.
https://github.com/prateekbh/preact-material-components/blob/master/LayoutGrid/LayoutGrid.jsx#L106
