### ISSUE TITLE
Select - Mobile

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#404]
On mobile (Safari on iOS 11), when I tap into a Select menu I cannot tap off of the Select menu to close it. I must choose an option to close the Select menu.

**Comment by prateekbh** [comment]
lemme check in android chrome

**Comment by prateekbh** [comment]
works in chrome android, can you raise a bug with mdc-web?

**Comment by mellogarrett** [comment]
mdc-web issue [here](https://github.com/material-components/material-components-web/issues/1605)

**Comment by mellogarrett** [comment]
Found out this is because iOS doesn't emit a click event if the element you are tapping on isn't considered "clickable".

Workaround is setting all elements as "clickable"

```
@supports (-webkit-overflow-scrolling: touch) {
  /* CSS specific to iOS devices */
  * {
    cursor: pointer;
  }
}
```
