### ISSUE TITLE
Theme - Radio Buttons

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#405]
Radio buttons are using the primary color theme whereas the [mdc docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-radio#user-content-theming) say they should use the secondary color theme

**Comment by prateekbh** [comment]
Can u verify if this was changed in the latest release?

**Comment by mellogarrett** [comment]
How can I check?

**Comment by prateekbh** [comment]
there is a changelog for mdc-web

**Comment by prateekbh** [comment]
actually this should be purely on css... and we dont change anything in css... makes it strange

**Comment by prateekbh** [comment]
is it still happening @mellogarrett ?
