### ISSUE TITLE
Text - Label Position

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#407]
The `Textfield` component when using either the `multiline` or `fullwidth` option has odd label placement.

multiline:
<img width="224" alt="screen shot 2017-11-17 at 2 30 07 pm" src="https://user-images.githubusercontent.com/9908831/32965227-eb9eef1e-cba3-11e7-9bc4-80a95ac3a8ec.png">

fullwidth:
<img width="511" alt="screen shot 2017-11-17 at 2 30 26 pm" src="https://user-images.githubusercontent.com/9908831/32965233-f31498d4-cba3-11e7-9673-d131c9af0228.png">

Is this an MDC-Web bug?

**Comment by mellogarrett** [comment]
Actually, it looks like MDC Web doesn't support labels for fullwidth text fields. I can submit a PR with logic to remove the label if `fullwidth={true}`, if desired?

**Comment by mellogarrett** [comment]
Also, for the `multiline` it looks like the error is because the outer div has the class of `mdc-textfield--multiline` when it should be `mdc-textfield--textarea`

**Comment by prateekbh** [comment]
@mellogarrett plz feel free to go ahead and send a PR

**Comment by filoozom** [comment]
We've already got two breaking changes for 0.25, might as well rename the whole `multiline` prop to `textarea`.

**Comment by mellogarrett** [comment]
1) Where is the class `mdc-textfield--multiline` coming from?

2) What's the best process for making local changes and testing their outcome?

**Comment by prateekbh** [comment]
a. class is coming from `TextField.jsx`

b. you can use the `sample` folder to test anything rough

**Comment by mellogarrett** [comment]
a. I see `className` being passed in as a prop. Is it there?

b. What are the steps to test something in `sample`?

**Comment by prateekbh** [comment]
b. steps: 
`webpack -w` and `http-server .`

a. https://github.com/prateekbh/preact-material-components/blob/master/TextField/TextField.jsx#L52

**Comment by mellogarrett** [comment]
I can't get a `TextField` to render in sample. I just keep getting this:

<img width="1440" alt="screen shot 2017-11-21 at 10 23 04 am" src="https://user-images.githubusercontent.com/9908831/33080435-15ad5c64-cea6-11e7-96bd-09f1f92686c6.png">

**Comment by prateekbh** [comment]
in root
0.) npm i on latest master
1.) `npm run build`
in sample 
2.) `webpack -w`
3.) `http-server .`


also do u slack?

**Comment by mellogarrett** [comment]
Yea, I'm a Slacker :)

**Comment by prateekbh** [comment]
https://preact.slack.com -> prateekbh

**Comment by mellogarrett** [comment]
Says I have to have a `@developit.ca` email address

**Comment by prateekbh** [comment]
gimme ur mail id

**Comment by mellogarrett** [comment]
garrett6346@gmail.com

**Comment by prateekbh** [comment]
sent

**Comment by mellogarrett** [comment]
Fixed by #412
