### ISSUE TITLE
Persistent drawer is not drawing any children

### ISSUE THREAD

**Issue by iamvijaydev** [prateekbh/preact-material-components#417]
There is a bug with PersistentDrawer. The render doesn't use `{props.children}` to render its children.

This line here: https://github.com/prateekbh/preact-material-components/blob/master/Drawer/Drawer.jsx#L191 should be like this:

`<nav className="mdc-persistent-drawer__drawer">{props.children}</nav>`

Currently, it's like this: 

`<nav className="mdc-persistent-drawer__drawer" />`

**Comment by sumiet** [comment]
@prateekbh I am working on this fix, can you help me with the commands to run the code in sample folder.

**Comment by filoozom** [comment]
Please have a look at this PR: https://github.com/prateekbh/preact-material-components/pull/420/files
