### ISSUE TITLE
ES6 module support sans build step

### ISSUE THREAD

**Issue by xxgreg** [prateekbh/preact-material-components#418]
Is it possible to use preact-material-components directly in the browser via ES6 modules without a build step?

For example the following works in Chrome:
```
import {h, render} from './node_modules/preact/dist/preact.esm.js';
render(h('div', {}, 'oi'), document.body);
```

I would like to be able to do this:
```
import {h, render} from './node_modules/preact/dist/preact.esm.js';
import TextField from './node_modules/preact-material-components/TextField/index.js';
render(h(TextField), document.body);
```

If this isn't supported - then consider this a feature request.

Cheers!

**Comment by prateekbh** [comment]
https://unpkg.com/preact-material-components@1.3.1/index.js
is served as an **esm**

please let us know if you were looking for anything else.

**Comment by xxgreg** [comment]
Thank you!  I must be blind ;)
