### ISSUE TITLE
Publish pre-compiled package to npm.

### ISSUE THREAD

**Issue by vaibhavkhl12** [prateekbh/preact-material-components#442]
[create-react-app](https://github.com/facebookincubator/create-react-app) prod build not able to minify this package. Read more [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) about this issue.

**Comment by prateekbh** [comment]
we do export an ES5 version: 
https://unpkg.com/preact-material-components@1.3.1/dist/index.js

**Comment by vaibhavkhl12** [comment]
thanks :)
