### ISSUE TITLE
Select aria-selected not updating correctly

### ISSUE THREAD

**Issue by mellogarrett** [prateekbh/preact-material-components#445]
If you pass `selectedIndex=null` to a Select component, it does not set all of its items to `aria-selected: false` like you would expect.

**Comment by prateekbh** [comment]
ohh nice catch

**Comment by mellogarrett** [comment]
This has been fixed in #447 

`material-components-web` did not like having `selectedIndex` set to null. It updates the aria-selected attr correctly, however, when you set it to -1 instead.
