### ISSUE TITLE
105:31-43 "export 'MDCTextfield' was not found in '@material/textfield/'

### ISSUE THREAD

**Issue by IndeDude** [prateekbh/preact-material-components#481]
`dependencies {
...
"preact-material-components": "^1.3.3",
...
}`

Started getting this error after shifting project to my Ubuntu 16.04 LTS platform from MacBook Pro.

**Comment by prateekbh** [comment]
ummm... using TS?

**Comment by mellogarrett** [comment]
Case sensitivity issue. The module is actually “MDCTextField” with a capital “F”

**Comment by prateekbh** [comment]
does this solve for u @IndeDude ?
