### ISSUE TITLE
Select component displays its items in a wrong position when placed inside a Dialog

### ISSUE THREAD

**Issue by pmbanugo** [prateekbh/preact-material-components#483]
When I used the select component inside a dialog, it display its items when clicked at the bottom of the dialog. 

This is how it renders outside of a dialog.

<img width="887" alt="screen shot 2017-12-20 at 17 03 35" src="https://user-images.githubusercontent.com/4036118/34515939-e96d75da-f074-11e7-8dfc-cd7b405f8c61.png">

Inside a dialog it displays like this

<img width="965" alt="screen shot 2017-12-20 at 17 02 18" src="https://user-images.githubusercontent.com/4036118/34515967-07ab236c-f075-11e7-8422-536b4e6b85fe.png">
<img width="366" alt="screen shot 2017-12-20 at 17 10 59" src="https://user-images.githubusercontent.com/4036118/34515971-0a9a807c-f075-11e7-87d4-814c4ad940f9.png">

**Comment by mellogarrett** [comment]
@pmbanugo This is actually a bug in `material-components-web`, which you can see here: https://github.com/material-components/material-components-web/issues/719
This project just wraps `material-components-web`
