### ISSUE TITLE
MDC List with avatar list class

### ISSUE THREAD

**Issue by heat** [prateekbh/preact-material-components#548]
MDC List should be awared about avatar list item with class `mdc-list--avatar-list`. I have not tested yet but  the componet that exists is a ListItemAvatar [MDC LIST](https://material.io/components/web/catalog/lists/#making-a-graphic-an-avatar)

**Comment by cromefire** [comment]
Should work: https://github.com/prateekbh/preact-material-components/blob/87f9dd2dc467e373c110a44f65b2ae15af6c622f/ts/List/index.tsx#L161
