### ISSUE TITLE
Textfield set validity

### ISSUE THREAD

**Issue by 7Ds7** [prateekbh/preact-material-components#555]
I do not seem to be able to set the validity of a textfield programatically or trough props

given the following input
```<TextField label="Street Address" id="street_name" helperTextValidationMsg="Invalid" valid="false" required/>```

Checked the issues before and this one https://github.com/prateekbh/preact-material-components/issues/332 lead to a merge in which the valid prop could be set to a textfield, i am using the latest version 1.3.5 and it is not working nor i see any method in the textfield input element to trigger/set it. 

Any hint on how this can be done?

**Comment by 7Ds7** [comment]
Ok it seems that validity={false} and not validity="false" works but isn't there any method that we can call on the input element that triggers it ?

**Comment by mellogarrett** [comment]
You'd probably want to store a `valid` variable in your app state somewhere and set its value via an `onChange` handler on the `TextArea` component

**Comment by mellogarrett** [comment]
```
import { h, Component } from "preact";

export default class TextArea extends Component {
  constructor() {
    this.state = {
      valid: true;
    }
  }

  validateTextField(e) {
    // validate your text content (e.target.value)
    // if necessary, toggle valid state
    this.setState(prevState => {
      this.setState({
        valid: !prevState.valid
      });
    });
  }

  render() {
    <TextArea 
      valid={this.state.valid}
      onChange={this.validateTextField.bind(undefined, e)}
    />
  }
}
```

**Comment by 7Ds7** [comment]
Humm, ok but that means onde need to have app states for each textfield used right ?
Also when using helperTextValidationMsg it does not seem to show when the field goes invalid

**Comment by mellogarrett** [comment]
Only if you wish to control validation. You could always store this state in a parent component and pass it down via props.

We'll definitely need to look at the `helperTextValidationMsg` issue

**Comment by prateekbh** [comment]
<TextField ref={txtField=>{this.txtField = txtField}} label="Street Address" id="street_name" helperTextValidationMsg="Invalid" valid="false" required/>

`this.ref.txtField.MDComponent.valid = false`

**Comment by 7Ds7** [comment]
Thank to you both, i will figure out a way to manage with the ref attribute, but the 'helperTextValidationMsg' not appearing is a known issue of the current version right ?

**Comment by prateekbh** [comment]
yep will check

**Comment by prateekbh** [comment]
its mostly adding a condition here:
https://github.com/prateekbh/preact-material-components/blob/master/TextField/TextField.jsx#L166

**Comment by prateekbh** [comment]
@7Ds7 try this
```<TextField
            helperText="helper text validation message"
            helperTextValidationMsg
            required
          />```

**Comment by 7Ds7** [comment]
Yes that seems to work, thank you @prateekbh

**Comment by 7Ds7** [comment]
With the last markup format everything works, also without the ref attribute works by setting the input parent mdc-text-field like so

`input.closest('.mdc-text-field').classList.add('mdc-text-field--invalid');`

I understand that this might not change Input component state, but it might be helpful to leave here if someone was just interested in the display functionality of the component, as i was

**Comment by prateekbh** [comment]
a manual call to `classList.add` might get overridden by preact's diffing algo
