### ISSUE TITLE
Errors when trying to import .scss files in TextField

### ISSUE THREAD

**Issue by ThisKappaIsGrey** [prateekbh/preact-material-components#583]
Hi, I tried `@import "preact-material-components/TextField/_mixins.scss";` in order to use the sass mixins to style the textbox, however i get this error:
`@import "bottom-line/mixins";
^
      File to import not found or unreadable: bottom-line/mixins.`
I want to change the text label color, and I'm using sass. Thank you for your help! 😄 

P.S:
How do I change the label color in general? I'm really confused on how to style Textfield and other preact-material-components in general.. some help would be great! Thank you so much!
I'm also pretty new to Sass too...

**Comment by prateekbh** [comment]
oh yeah! that is because they have created a new component `bottom-line`.
This will be fixed in 1.3.6 version

**Comment by prateekbh** [comment]
also did you just tried doing it with normal css selector higher specificity?

**Comment by ThisKappaIsGrey** [comment]
@prateekbh How do I change the label color in general? I also have issues with changing the colors of the resting switch with scss, I imported the .scss file from `preact-material-components/mdc-switch` and in my style.scss I tried to do `@include mdc-switch-track-color($color)` in a subclass but I couldn't change the track color. Please help me.  I also tried to do it with css selectors but it didn't work.
Thank so much!

**Comment by cromefire** [comment]
Should be fixed
