### ISSUE TITLE
What is the proper way to use sass mixins?

### ISSUE THREAD

**Issue by ThisKappaIsGrey** [prateekbh/preact-material-components#593]
I'm not sure on how you would use sass mixins in this project.
This is what I tried:
in my component.js: 
`import "preact-material-components/Switch/mdc-switch" 
  import style from "./style" 
  ... 
  <Switch className={style.switch} />`
in my style.scss:
`@import "preact-material-components/Switch/_mixins.scss";
  .root{
  ...
     .switch {
        $color: #fff;
      @include mdc-switch-track-color($color);
      @include mdc-switch-knob-color($color);
      @include mdc-switch-focus-indicator-color($color);
     }
  }
`
It still changes the switch color to the secondary color that i've set. Although I could change the switch color with the secondary color, I would like to use the mixins in other parts of my application.
Thank you for your help!

**Comment by cromefire** [comment]
The scss in this is just copied from [material-components/material-components-web](https://github.com/material-components/material-components-web) you should look / ask there.
