### ISSUE TITLE
Remove temp fix for select floating label

### ISSUE THREAD

**Issue by YePpHa** [prateekbh/preact-material-components#611]
This is for v0.31.0

https://github.com/prateekbh/preact-material-components/blob/master/Select/Select.jsx#L41

**Comment by prateekbh** [comment]
did anything change in 0.31.0 that helps us remove this?

**Comment by YePpHa** [comment]
Yup, they applied a fix for it. I haven't tested it myself yet, but I assume that it will work.

**select:** pre-selected option correctly floats label ([#2125](https://github.com/material-components/material-components-web/issues/2125)) ([fac0d03](https://github.com/material-components/material-components-web/commit/fac0d03))

**Comment by YePpHa** [comment]
I did a test on the sample page and it seems like the bug is still there. We should just keep this temporary fix for now.

**Comment by cromefire** [comment]
How about now?

**Comment by cromefire** [comment]
This one doesn't seem to be applicable at all anymore
