### ISSUE TITLE
Implement Chips Icon

### ISSUE THREAD

**Issue by YePpHa** [prateekbh/preact-material-components#612]
I've started work [here](https://github.com/YePpHa/preact-material-components/tree/feat/chips/leading-icon) but it still needs the new version of mdc.

**Comment by prateekbh** [comment]
@YePpHa can we add this in 1.3.6?

**Comment by YePpHa** [comment]
@prateekbh sure, I will make a PR when I get home

**Comment by prateekbh** [comment]
@YePpHa can you please add the docs page as well with this! so we'll be almost good to publish

**Comment by YePpHa** [comment]
@prateekbh sure I will start work on it
