### ISSUE TITLE
[Checkbox] setIndeterminate function lacks return-type annotation, cannot pass typescript type check

### ISSUE THREAD

**Issue by Huanghuiying0624** [prateekbh/preact-material-components#617]
When I use Checkbox of this lib, get typescript error:
ERROR in [at-loader] ./node_modules/preact-material-components/Checkbox/index.d.ts:16:3
    TS7010: 'setIndeterminate', which lacks return-type annotation, implicitly has an 'any' return type.

**Comment by YePpHa** [comment]
Fixed in #618.
