### ISSUE TITLE
Focus circle persists after tap or click

### ISSUE THREAD

**Issue by jennydaman** [prateekbh/preact-material-components#625]
![image](https://user-images.githubusercontent.com/20404439/36878800-97dfeeea-1d8e-11e8-9801-d244db0c830b.png)

Is there a safe and proper way of making the focus circle disappear after tap/click?

**Comment by developit** [comment]
You should be able to attach this event handler:

```js
let lock = 0;
addEventListener('mouseup', e => {
    if (lock) return;
    let { target } = e;
    do {
        if (target.classList && target.classList.contains('mdc-ripple-upgraded--foreground-activation')) {
            lock++;
            fireEvent(target, 'pointerup');
            fireEvent(target, 'mouseup');
            fireEvent(target, 'touchend');
            lock--;
            return;
        }
    } while ((target=target.parentNode));
}, { passive: true });
```

**Comment by jennydaman** [comment]
Looks scary, but thanks!

**Comment by prateekbh** [comment]
this an other ripples are long pending bugs on mdc-web.

I wonder if we should have a fix available, under `experimental` folder or something.

**Comment by jennydaman** [comment]
Before submitting this issue, i searched intensively for a solution upstream. Apparently, the persistent ripple is an intentional feature, it is how they handle :focus state for users using the tab key and no mouse. I'll find and link the original PR when i get home. 

My opinion is that this effect is distasteful. The issue does not exist with MDL, but MDC will supersede MDL so I'm trying to stay on the bleeding edge...

**Comment by jennydaman** [comment]
https://github.com/material-components/material-components-web/issues/809#issuecomment-353147714

**Comment by prateekbh** [comment]
![bug-vs-feature](https://user-images.githubusercontent.com/5960497/36996848-a8f9909c-206c-11e8-8dd3-ef6fc93494da.jpg)

#NotABug 😆

**Comment by jennydaman** [comment]
I'll summarize my findings for future reference.

- [preact-material-components (MDC for web)](https://github.com/prateekbh/preact-material-components): `:focus` is ugly, no tooltip
- [preact-mdl](https://github.com/developit/preact-mdl): input elements `:focus` correctly, looks nice, but the library is outdated eg. [tabs](https://github.com/developit/preact-mdl) don't have animations
- preact-compat + [material-ui](http://www.material-ui.com/): additional and unique components, but modals don't work
