### ISSUE TITLE
Subfolder CSS is not getting copied

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#660]
Our Css MigrationWebpackPlugin is not copying subfolder css inside a components folder 
e.g.

`https://unpkg.com/@material/drawer@0.30.0/` has `persistent`, `permanent` etc which has scss inside it.

but no such files are in `https://unpkg.com/preact-material-components@1.3.7/Drawer/`

**Comment by prateekbh** [comment]
@wuweiweiwu can i assign this to you?

**Comment by wuweiweiwu** [comment]
@prateekbh Yep! I'm working on it now!

**Comment by cromefire** [comment]
Seems to be fixed
