### ISSUE TITLE
Consider numeric z attribute for Elevation

### ISSUE THREAD

**Issue by shyndman** [prateekbh/preact-material-components#72]
Have you considered having a single numeric z attribute on the Elevation component? 

ie.
```jsx
<Elevation z="1"/>
<Elevation z="2"/>
<Elevation z="3"/>
...
```

That way it's easier to configure with a variable:

```jsx
<Elevation z={myComputedElevation} />
```

And it's also easier to understand. From an API standpoint, having one boolean attribute per `z` is a little weird because it suggests that you can set  multiple `z`s on the same component. You don't want people to think you can use this component like this:
```jsx
<Elevation z1={true} z13={true} z25={true}/>
```

**Comment by prateekbh** [comment]
This'll be a part of 1.0 launch, if you wish feel free to assign this t yourself and raise a PR.
Else I'll take it up before launch

**Comment by prateekbh** [comment]
merged in master, right now both ways will work. removing earlier method from documentation and will remove gradually
