### ISSUE TITLE
Floating label and placeholder overlap

### ISSUE THREAD

**Issue by habelMarottipuzha** [prateekbh/preact-material-components#746]
If we add form field of type date, we will get the floating label overlapped with placeholder.
code like
`<input type='date' className="mdc-textfield__input" {...restProps} />`

Full fiddle [http://jsfiddle.net/jyc5jgg2/](http://jsfiddle.net/jyc5jgg2/)

**Comment by habelMarottipuzha** [comment]
@prateekbh  Clicking on field label currently not focusing text field. We have to click outside of field label to focus text field.
It works perfectly in mdc.

**Comment by prateekbh** [comment]
@habelMarottipuzha is this reproducible in the same jsFiddle link as well?
