### ISSUE TITLE
Card: '16-9' is not valid JSX

### ISSUE THREAD

**Issue by SleeplessByte** [prateekbh/preact-material-components#749]
When using JSX, there is no easy way to make a card's media 16:9 ratio, as HTML attributes may never start with a number.
```JSX
<Card>
  <Card.Media 16-9 />
</Card>
```

You can't get around this by quoting the parameter:

```JSX
<Card>
  <Card.Media '16-9' />
</Card>
```

Instead you must resort to something like:
```JSX
const sizing = { '16-9': true }

// [...]

<Card>
  <Card.Media {...sizing} />
</Card>
```

I suggest adding the alias `sixteenByNine` or even dropping the [invalid] prop name.

**Comment by prateekbh** [comment]
would you like to PR?

**Comment by aravindballa** [comment]
Is anyone working on this? Or can I take this up in my free time? 😀

**Comment by cromefire** [comment]
Fixed
