### ISSUE TITLE
CardActionButton does not behave like Button

### ISSUE THREAD

**Issue by SleeplessByte** [prateekbh/preact-material-components#750]
The `Button` component becomes an `a` if an `href` is given ([source](https://github.com/prateekbh/preact-material-components/blob/master/Button/Button.jsx#L25)), but the `Card.ActionButton` is always forced a button ([source](https://github.com/prateekbh/preact-material-components/blob/master/Card/Card.jsx#L37)).

According to the [spec](https://material.io/guidelines/components/cards.html#cards-content-blocks), the actions in a card may be any action, including any type of `Button`, even though raised buttons are usually discouraged if they are going to show up on all cards.

It would be best to actually import `Button` here, and let that handle the code.

Here is another way of handling this: https://jamesmfriedman.github.io/rmwc/usage. In that library a `tag` prop is available on *all* library components, which overrides the default when given. For example, sometimes a card may be an `<article> ... </article>` and sometimes it may be an `<aside> </aside>`, as well as other possibilities. Adding that feature makes it easier to stay semantic.

**Comment by prateekbh** [comment]
Actually this is super easy if you just use `import Button from ../Button` but the problem is that mdc-web does not support it. And it used to be like that which changed mid way.

Plus do you really have a use case of navigating somewhere from a dialog button? If yes, its a super simple fix.

Lemme know what u think?

**Comment by cromefire** [comment]
It should be the case now
