### ISSUE TITLE
Update gh-pages

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#76]
1. z prop for elevation
2. grid-layout
3. new List Items(Divider, Icon, Avatar)
4. basic select component

**Comment by prateekbh** [comment]
1 3 and 4 r done

**Comment by prateekbh** [comment]
@IrregularShed will you be able to add a documentation page in `gh-pages` branch?
tak e look at other pages component it is pretty straight forward.

**Comment by IrregularShed** [comment]
Yep, will do. I've been away for the past five days, otherwise I'd have already started :)

**Comment by prateekbh** [comment]
no probs, just trying to triage the issues to launch a stable.
Actually Stable is pushed a little with the release of mdc-web 0.9.0 and I am stuck in some talk and workshops to be delivered.

**Comment by prateekbh** [comment]
Thanks @IrregularShed, I guess we're good to come out of beta now
