### ISSUE TITLE
Using Select with dynamic props causes issues

### ISSUE THREAD

**Issue by laggingreflex** [prateekbh/preact-material-components#78]
I'm pretty new to material so please let me know if I'm supposed to do things some other way. 

`Select` component has a "hintText" which is rendered like this:

```
<div class="mdc-select">
  <span class="mdc-select__selected-text"> "hintText" </span> // <-- 
  <div class="mdc-simple-menu">
    <ul>
      <li class="mdc-list-item"> Option 1 </li>
      ...
```

When you choose "Option 1" it re-renders the component replacing the span element where "hintText" originally was, with "Option 1". 

```
<div class="mdc-select">
  <span class="mdc-select__selected-text"> "Option 1" </span>  // <--
  <div class="mdc-simple-menu">
    <ul>
      <li class="mdc-list-item"> Option 1 </li>
      ...
```

But this causes problems because in my app when I select Option 1 it changes state and triggers `render()` function which re-renders the `Select` with the original "hintText", i.e. it undoes or conflicts with the MD Select's behaviour of replacing the hintText with Option 1.

Am I missing something that could be used to prevent this or tell the Select component to use the selected item as hinttext when available from withing the MD ecosystem itself? Or shall I just manage "hintText" myself replacing it with the selected Option 1 in my app's render function?

**Comment by prateekbh** [comment]
can you paste your preact code for your `render` function here ?

**Comment by prateekbh** [comment]
Agreed I see the issue here,
opened #79 for this one. will release with stable. Mostly this week.

**Comment by prateekbh** [comment]
@laggingreflex  1.0.0-beta.1 is released please try that out.
An example in the demo site is also included.
Sorry for delay
