### ISSUE TITLE
Tabs within TabBarScroller are initialized multiple times

### ISSUE THREAD

**Issue by Dramloc** [prateekbh/preact-material-components#795]
I found an issue with `Tabs` within a `Tabs.TabBarScroller`. Here is a simple example to reproduce the issue (this can also be reproduced on the [Tabs Scroller example](https://material.preactjs.com/component/tabs)) :
```jsx
<Tabs.TabBarScroller>
	<Tabs scroller>
		<Tabs.Tab>1</Tabs.Tab>
		<Tabs.Tab>2</Tabs.Tab>
		<Tabs.Tab>3</Tabs.Tab>
	</Tabs>
</Tabs.TabBarScroller>
```

### Details
When `Tabs` are used within a `Tabs.TabBarScroller`, this causes `MDCTabBar` to be constructed multiple times :
- Once in the [`MDCTabBarScroller.initialize`](https://github.com/material-components/material-components-web/blob/d9d695a5c6739e73ebcffcd0eb28ce8cd1c0e8d2/packages/mdc-tabs/tab-bar-scroller/index.js#L34) method
- Once in the [`Tabs.componentDidMount`](https://github.com/prateekbh/preact-material-components/blob/ac8a8556d4bb95d08650182be2520f00c1c17083/Tabs/Tabs.jsx#L31) method

This also causes `MDCTab` to be constructed multiple times as they are initialized in the [`MDCTabBar.initialize`](https://github.com/material-components/material-components-web/blob/d9d695a5c6739e73ebcffcd0eb28ce8cd1c0e8d2/packages/mdc-tabs/tab-bar/index.js#L50) method.

As `MDCTab` are created multiple times, the following error occurs when switching tab :
```Invalid tab component given as activeTab: Tab not found within this component's tab list```
These errors can be seen in the console on the [Tabs Scroller example](https://material.preactjs.com/component/tabs).

### Potential fixes
I haven't found a clean fix for now. We might want to condition `MDCTabBar` initialization on `scroller` property but we still need to access `MDCTabBar` instance to make `activeTabIndex` work :

```js
componentDidMount() {
	if (!this.props.scroller) {
		this.MDComponent = new MDCTabBar(this.control);
	}
	// This will break if `props.activeTabIndex` is set
	setActiveTabIndex(defaultProps, this.props, this.MDComponent);
}
```

Another idea would be to merge `Tabs` and `Tabs.TabBarScroller` components in a single component :

```jsx
// would only render tab-bar
<Tabs activeTabIndex={1}>
	<Tabs.Tab>1</Tabs.Tab>
	<Tabs.Tab>2</Tabs.Tab>
	<Tabs.Tab>3</Tabs.Tab>
</Tabs>

// would render tab-bar wrapped in a tab-bar-scroller
<Tabs activeTabIndex={1} scroller>
	<Tabs.Tab>1</Tabs.Tab>
	<Tabs.Tab>2</Tabs.Tab>
	<Tabs.Tab>3</Tabs.Tab>
</Tabs>
```

This allow us to access `MDCTabBar` instance to handle `activeTabIndex` changes and might make more sense (`scroller` property makes little sense if `Tabs` are not wrapped in a `TabBarScroller`).

Let me know what you think.

**Comment by prateekbh** [comment]
Merging the two rounds reasonable. Do you want to open a PR for this? Else I'll take it but might take a few days
