### ISSUE TITLE
Switches don't detect mouse clicks near top

### ISSUE THREAD

**Issue by appsforartists** [prateekbh/preact-material-components#85]
I can't click the Dark Mode switch on the Chromebook Pixel; but I can tap it.  Most likely, someone is doing something like `TouchEvent in document ? addEventListener('touchdown') : addEventListener('click')`

Not sure if this is a bug for you here or @traviskaufman on mdc-web.

**Comment by prateekbh** [comment]
@appsforartists  Can you check if its working here
http://material-components-web.appspot.com/switch.html

**Comment by appsforartists** [comment]
On both that page and on the Dark Mode slider on the docs page, the switches toggle if I click near the bottom of the track, but not if I click near the top.

(Additionally, my cursor turns into a pointer over some regions of the disabled switches, although it probably shouldn't.)

**Comment by IrregularShed** [comment]
@appsforartists It looks as if this is a bug in mdc-web - sorry @traviskaufman. I'm seeing the same behaviour (pointer becoming a cursor) on MS Edge and Chrome for Windows.

The implementation is purely (S)CSS applied to a checkbox and a pair of decorative divs to provide the background and the slider image, and Preact Material Components is just creating the markup to match the spec here: https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch

**Comment by prateekbh** [comment]
@appsforartists  can you please open the same in `mdc-web`.
