### ISSUE TITLE
Exlude package-lock.json from prettier ci

### ISSUE THREAD

**Issue by cromefire** [prateekbh/preact-material-components#854]
As package-lock.json is auto generated it shouldn't be checked for style

**Comment by cromefire** [comment]
I don't think I saw an issue with this again but it's probably better to just exclude it

**Comment by cromefire** [comment]
@prateekbh this is still a thing, can you fix it?

**Comment by prateekbh** [comment]
I don't know let's put it to 2.0

**Comment by cromefire** [comment]
It's not version dependent as you need to configure it with prettier CI just wanted to poke it
