### ISSUE TITLE
Chip: filter chips "selected" class out of sync with bound value?

### ISSUE THREAD

**Issue by shc023** [prateekbh/preact-material-components#860]
minimal repro here: http://jsfiddle.net/secvkhrf/

Not sure if I'm doing something wrong, but I'm just trying to change a state value when clicking the chip, which is also bound to the chip's |selected| property.

If you try clicking the chip in the fiddle, you'll see that on the first click, the state's value did change as expected, but the --selected class did not go away, so the chip is still look selected. Subsequent clicks on the chip will then toggle both the state value and the --selected class, so they will be forever out of sync (i.e. value says false when UI displays chip as selected, and vice versa).

Am I doing something wrong? or is mdc doing something in the background that's conflicting with my onClick handler?

**Comment by prateekbh** [comment]
Its the way that chipset and chips are built that they are not very prop friendly.
If its only 1 chip, I suggest it using without chipset, otherwise use `chipsetRef.MDComponent.select(chipRef.MDComponent)`.

Not closing this, as we should implement a more friendly API here

**Comment by prateekbh** [comment]
This should be fixed with 2.0
