### ISSUE TITLE
Double docs

### ISSUE THREAD

**Issue by dandv** [prateekbh/preact-material-components#869]
I thought I was seeing double, but for Chrome and FF concur: the documentation on the [home page](https://material.preactjs.com/) does show up repeated. Search for "opinionless" on the page, and you'll find `preact-material-components is a thin opinionless wrapper around material-components-web.` twice. One way to reproduce this is to scroll to the bottom of a page and reload.

![preact md double](https://user-images.githubusercontent.com/33569/42988147-68c5c374-8bb0-11e8-96a2-56dc459485c0.gif)

**Comment by prateekbh** [comment]
ohhh right! that explains the double screenshot in the tests... Thanks.. Yep definitely needs a fix
