### ISSUE TITLE
Use a permanently visible drawer for the site

### ISSUE THREAD

**Issue by dandv** [prateekbh/preact-material-components#871]
A bit annoying when exploring components that when you reach the end of a component's docs, you need to scroll up then open the drawer, then find your place and click on another component. https://material.io/design/components/ has the drawer permanently visible per the guideline,

> Permanently visible drawer: When users need to switch destinations frequently (and screen size allows), a permanently visible drawer can be used.

https://material-components.github.io/material-components-web-catalog/#/component/drawer does it best IMO.

**Comment by cromefire** [comment]
I think we fixed this
