### ISSUE TITLE
How to change the default color?

### ISSUE THREAD

**Issue by anuragnagarkota** [prateekbh/preact-material-components#877]
Hey

How can I change the default color of my app. ???

**Comment by prateekbh** [comment]
Here's a small documentation around the same: https://material.preactjs.com/component/theme/

**Comment by prateekbh** [comment]
gist being: declare custom vars as: 
--mdc-theme-primary, --mdc-theme-secondary and so on

**Comment by prateekbh** [comment]
I'll write about this in the material template repo. Sounds good?

**Comment by cromefire** [comment]
@wei simply add the custom vars to the :root selector like:
```
:root {
    --mdc-theme-primary: <value>;
}
```
Or to override global values by putting them on a normal class/id selector. 
Using css custom vars has a syntax like:
`<property>: var(--mdc-theme-primary);`
But the mwc should include everything you need out of the box. 
-------
All the variables: https://material.io/develop/web/components/theme/ under `Non-Sass customization` 
Color tool for selecting colors: https://material.io/tools/color/

**Comment by wei** [comment]
@prateekbh that will be awesome. I'm grateful for the help!

Thanks @cromefire, I've never used `:root` and `var()` in css so I thought it was sass : p. It works great now!

I ended up installing `sass-loader` and `node-sass`, renamed `src/style/index.css` to `.scss`, then added the following to allow theme variable overwrites:
```
$mdc-theme-primary: red;

@import 'preact-material-components/material-components-web.scss';
```
I can also import scss for each component separately. It works great!

Do you know what I need to do to access theme variables `$mdc-theme-primary` in a different scss file. For example, `components/header/style.scss` is imported in `components/header/index.js`, and `$mdc-theme-primary` appears to be undefined there. Just curious what is the best practice to use variables in scss files inside each component? 🙇

**Comment by cromefire** [comment]
This is how I like to do it:
https://github.com/cromefire/preact-mwc-styled#usage
Look at `sass-resource-loader`.

**Comment by prateekbh** [comment]
Added a small writeup here: https://github.com/preactjs-templates/material/blob/master/README.md
