### ISSUE TITLE
Presentation website shows the homepage text twice at first load

### ISSUE THREAD

**Issue by renanlecaro** [prateekbh/preact-material-components#881]
Step to reproduce : 

1/ Open https://material.preactjs.com/ in a private navigation window

Expected behavior : show the homepage content once
See behavior : the content is shown twice

I suspect there's some service worker misconfiguration here 

Attached video : https://www.youtube.com/watch?v=iopYx8VFxIg

**Comment by prateekbh** [comment]
This was fixed in a recent deployment. But shouldn't be happening in a private window.

Your you tube vid is not available

**Comment by renanlecaro** [comment]
@prateekbh sorry for the video, i just switched it to unlisted.

**Comment by prateekbh** [comment]
it isnt really happening for me. can you close all incognitos and try again?

**Comment by prateekbh** [comment]
hmm i know where its coming from, will fix it tomorrow

**Comment by prateekbh** [comment]
should be fixed now. please check

**Comment by renanlecaro** [comment]
Yes, issue fixed, nice :)
