### ISSUE TITLE
1.5.1-alpha1 from npm seems to be broken

### ISSUE THREAD

**Issue by krisboit** [prateekbh/preact-material-components#918]
Hey, i just stared a new project with preact, I installed the package from npm (1.5.1-alpha1) and i get this error
```
Build failed!

✖ ERROR [at-loader] ./node_modules/preact-material-components/Base/MaterialComponent.d.ts:3:27
    TS2307: Cannot find module './types'.
```

This is my preact component:
```
import './style.scss';
import { h, Component } from 'preact';

import Button from "preact-material-components/Button";

export default class App extends Component {
	render() {
		return (
			<div>
				<h1>Hello, World!</h1>
			</div>
		);
	}
}
```

**Note**: with 1.5.0 it works fine.

**Comment by prateekbh** [comment]
Cc: @cromefire_

**Comment by cromefire** [comment]
@krisboit Yes will fix it  suggesting you use the stable version for now, it has the same features
@prateekbh didn't you publish it to alpha channel, but instead to latest?

**Comment by cromefire** [comment]
@krisboit also suggesting that you try out if
``` typescript
import Button from "preact-material-components/ts/Button";
```
works for you, because that will make use of your own babel infrastructure, so no useless transforms are applied (at-loader should handle that correctly).
That's because `preact-material-components/Button` is already (fully) transpiled to ES5, which is unneeded for newer browsers.

**Comment by cromefire** [comment]
@prateekbh please unpublish `1.5.1-alpha1` and publish `1.5.1-alpha2` to `alpha` channel (using `npm publish --tag alpha`) because `npm` will install it for everyone who just types `npm install preact-material-components` which is bad for an alpha.
