### ISSUE TITLE
Add full support for "checked" property to Switch

### ISSUE THREAD

**Issue by mischkl** [prateekbh/preact-material-components#928]
At the moment the Switch component does not fully handle the `checked` property. Namely, if the `checked` property is set, the class `mdc-switch--checked` should be added to the top-level div (in addition to the class `mdc-switch`, which is also currently missing). See https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch#user-content-initially-on-switch

**Comment by prateekbh** [comment]
Is there a like some css bug that this causes?

Cuz I checked this was fine without adding the class.

**Comment by mischkl** [comment]
Hmm, it seems like this addition to the docs was just added for v0.39.0. TBH I haven't tested with that version but I suppose it is worth investigating.

**Comment by cromefire** [comment]
Will look into this
