### ISSUE TITLE
Programatically control active tab for tabbar

### ISSUE THREAD

**Issue by r1cs1** [prateekbh/preact-material-components#970]
Hi guys,

I'm trying to programatically control active tab for tabbar, however neither activeTabIndex on TabBar, nor active prop on Tab is working.

Am I missing something or that's expected?

Thanks,
Richard

**Comment by cromefire** [comment]
Can you share how you try to do this? I think I know what's going wrong and if so a fix is on the way.

**Comment by replaysMike** [comment]
Oh man I just came here to ask that exact question as well. I'll show you what I did, but it's an awful solution in my opinion but the docs here are pretty scarce in detail.

```
handleTabChange = (e) => {
	// todo: this feels old school, do Tabs component handle content selection?
	const targetName=e.toElement.getAttribute('tab');
	const panelsContainer = document.getElementById('panels');
	var panels = panelsContainer.getElementsByTagName('*');
	for(var i=0,len=panels.length; i<len; i++){
		panels[i].style = 'display: none;'
	const target = document.getElementById(targetName);
	target.style = 'display: block';
	};
}

render(props, state) {
	return (
		<div>
			<Tabs onClick={this.handleTabChange}>
				<Tabs.Tab tab="panel-1" active={true}><Icon>favorite</Icon>Texas Holdem</Tabs.Tab>
				<Tabs.Tab tab="panel-2">Blackjack</Tabs.Tab>
				<Tabs.Tab tab="panel-3">Guts</Tabs.Tab>
			</Tabs>
			<section id="panels">
				<p id="panel-1">Texas Holdem Content</p>
				<p id="panel-2" hidden={true}>Blackjack Content</p>
				<p id="panel-3" hidden={true}>Guts Content</p>
			</section>
		</div>
	);
}
```

I hope someone else can chime in and indicate the proper way to do things, I've spent a few hours looking at the examples and source with no answer.

**Comment by replaysMike** [comment]
In addition to that, for me I get this when trying to use the TabBar (since Tabs is marked as deprecated):

`Module not found: Error: Can't resolve 'preact-material-components/TabBar'`
¯\_(ツ)_/¯

**Comment by r1cs1** [comment]
Here's a dummy example, because my code too complex to paste here. I hope I didn't mess it up .

Also, I'm using 1.5.1-beta1 because that's the only one that compiles with little mods with my typescript setup

```
handleClick = event => {
  this.setState({ active: +event.target.dataset.index });
}

render() {
  return (
    <TabBar>
      <TabBar.Tab onClick={this.handleClick } data-index="0" active={this.state.active === 0}>A</TabBar.Tab>
      <TabBar.Tab onClick={this.handleClick } data-index="1" active={this.state.active === 1}>B</TabBar.Tab>
      <TabBar.Tab onClick={this.handleClick } data-index="2" active={this.state.active === 2}>C</TabBar.Tab>
    </TabBar>
  )
}
```

**Comment by cromefire** [comment]
Yes I think it's a thing that is linked to #931

**Comment by cromefire** [comment]
@replaysMike I think your version is too old for `TabBar`

**Comment by cromefire** [comment]
@r1cs1 your example seems fine, as long as that `+event.target.dataset.index` line works fine. I will look into getting that fixed.

**Comment by replaysMike** [comment]
@cromefire indeed you seem to be right, I'm running 1.5.0 (default installed for `npm install preact-material-components`)

**Comment by cromefire** [comment]
Yes the docs are already representing the beta version and there is currently no good way to see the older docs

**Comment by cromefire** [comment]
@r1cs1 Please try `1.5.1-experimental7` it should fix both `activeTabIndex` and `active`

**Comment by cromefire** [comment]
I'm not sure, if `active` is working, it seems to have problems, I don't even know if that's supported anymore or there may be a problem with `Tab` in general.

**Comment by r1cs1** [comment]
@cromefire now active seems to be working when it's set outside of TabBar. I mean if I set the state NOT via onclick event on the Tab elements. Basically what I want to achieve is to cancel tab switching based on some conditions. However it seems internal click handlers are more powerful :)

**Comment by r1cs1** [comment]
@cromefire  On the other hand, I always get the following error since 1.5.1-xxx

```
ERROR in [at-loader] ./node_modules/preact-material-components/Base/types.d.ts:2:11
    TS2322: Type 'T' is not assignable to type 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

ERROR in [at-loader] ./node_modules/preact-material-components/Base/types.d.ts:4:11
    TS2322: Type 'U' is not assignable to type 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```
Replacing it by this code seems to solve it, but not sure if it causes any other issues or if it's correct liek that:

```

export declare type OmitAttrs<T extends {
    [attr: string]: any;
}, O extends {
    [attr: string]: any;
}> = Pick<T, keyof { [K in Exclude<keyof T, keyof O>]: T[K] }>

```

**Comment by cromefire** [comment]
Yes that's something that needs to be changed doing that tomorrow (CEST).

**Comment by replaysMike** [comment]
Not trying to hijack the thread, but upgrading to latest preact didn't solve the issue. I even dumped node_modules and reinstalled, upgraded babel but still no luck. Odd.

```
× ERROR ./src/components/home/index.js
Module not found: Error: Can't resolve 'preact-material-components/TabBar' in .......
```

**Comment by prateekbh** [comment]
Yeah tabBar isn't really a prop friendly underneath.
Please use `.MDComponent.setActive()` on the ref of tabbar

**Comment by prateekbh** [comment]
Also same for Tabs

**Comment by prateekbh** [comment]
Example: https://1040718yoq.codesandbox.io

**Comment by r1cs1** [comment]
@prateekbh Thanks, man! `.MDComponent.activateTab(index)` on the TabBar works like a charm

**Comment by cromefire** [comment]
So as it seems to work like this I'll close it.

**Comment by thadeu** [comment]
> Example: https://1040718yoq.codesandbox.io
> 
> P.s. swipe left right for active tabs

what is this repository?

**Comment by prateekbh** [comment]
nuka carousel

**Comment by thadeu** [comment]
@prateekbh I'd like see the code

**Comment by cromefire** [comment]
https://codesandbox.io/s/1040718yoq
That looks like something that would be nice to include in the `2.0` Tabs (in like a subclass)

**Comment by thadeu** [comment]
@cromefire thanks so much!
