### ISSUE TITLE
TabBar Example - Missing css

### ISSUE THREAD

**Issue by chrisrymer** [prateekbh/preact-material-components#977]
I have just been taking a look at this and wanted to implement the TabBar. After following the docs (
https://material.preactjs.com/component/tabbar/) I received an error regarding the referenced css file.

```import 'preact-material-components/TabBar/style.css';```

Looking through the source I can see the css file does not exist and needs to be extracted from the master css file.

**Comment by prateekbh** [comment]
fixed in 1.5.2

**Comment by jimfilippou** [comment]
I. still have the issue
