### ISSUE TITLE
import base style.css errors on build

### ISSUE THREAD

**Issue by chrisrymer** [prateekbh/preact-material-components#978]
This is possibly a webpack issue and inexperience problem on my part. But after following the guidelines to allows all css to be loaded within the app

ie. ``` import 'preact-material-components/style.css'; ```

webpack throws a major hissy with the following

```Unrecognised input. Possibly missing opening '{' in /node_modules/preact-material-components/style.css (line 6, column 5136)```

**Webpack version:** 
"webpack": "4.2.0",
"webpack-cli": "^3.1.0",
 "webpack-dev-server": "^3.0.0"

**Webpack Config CSS Rules**
```
{
	// Transform our own .(less|css) files with PostCSS and CSS-modules
	test: /\.(less|css)$/,
	include: [path.resolve(__dirname, 'src/components')],
	use: ExtractTextPlugin.extract({
		fallback: 'style-loader',
		use: [
			{
				loader: 'css-loader',
				options: { modules: true, sourceMap: CSS_MAPS, importLoaders: 1, minimize: true }
			},
			{
				loader: `postcss-loader`,
				options: {
					sourceMap: CSS_MAPS,
					plugins: () => {
						autoprefixer({ browsers: [ 'last 2 versions' ] });
					}
				}
			},
			{
				loader: 'less-loader',
				options: { sourceMap: CSS_MAPS }
			}
		]
	})
},
{
	test: /\.(less|css)$/,
	exclude: [path.resolve(__dirname, 'src/components')],
	use: ExtractTextPlugin.extract({
		fallback: 'style-loader',
		use: [
			{
				loader: 'css-loader',
				options: { sourceMap: CSS_MAPS, importLoaders: 1, minimize: true }
			},
			{
				loader: `postcss-loader`,
				options: {
					sourceMap: CSS_MAPS,
					plugins: () => {
						autoprefixer({ browsers: [ 'last 2 versions' ] });
					}
				}
			},
			{
				loader: 'less-loader',
				options: { sourceMap: CSS_MAPS }
			}
		]
	})
},
```

The error seems to point to this line ```{--mdc-ripple-fg-opacity: .16}```. I am presuming this is something to do with css-loader not understanding this. I will update the module and see if that negates the issue.

**Comment by prateekbh** [comment]
oh your config does not recognizes css variables, i am not sure how to fix it though

**Comment by prateekbh** [comment]
just closing cuz its a webpack issue, feel free to comment

**Comment by chrisrymer** [comment]
OK understood. Thanks

**Comment by cromefire** [comment]
As `css-loader` and `postcss-loader` don't have problems with it, I would probably have a look on the `less-loader`.
