### ISSUE TITLE
Select seems to remembering state

### ISSUE THREAD

**Issue by lchimaru** [prateekbh/preact-material-components#984]
From last (1.5.2) update Select component seems to be working a little bit different. It seems to remembering chosen value even if it is rerendered . I believe none of option should be selected if component is mounting (if selectedIndex is not set), as it was working before. Please take at look at example from CodeSandbox:
https://codesandbox.io/s/xpq5z85vpq

**Comment by prateekbh** [comment]
U r showing hiding the component, why is that not supposed to remember state?

**Comment by prateekbh** [comment]
can you check if this was fine in 1.5.1?

**Comment by lchimaru** [comment]
Nope, none of those versions have Select/TextField components working different.

**Comment by lchimaru** [comment]
Yup, you're right, I didn't noticed that. So it looks like it's issue more for preact, not preact-material-components. I'm closing this issue, thanks for investigation :)

**Comment by cromefire** [comment]
I might not recall this correctly but this might actually be a browser thing
