### ISSUE TITLE
How to use permanent drawer with grid layout? 

### ISSUE THREAD

**Issue by Jamdan2** [prateekbh/preact-material-components#985]
Hello, I am new to these components and I would like to build a layout grid accompanied by a permanent side drawer. However, when I simply place the two components next to each other in the JSX markup one ends up on top of the other, which is not the desired behavior. The mdc docs make it sound like these components should just work together, so I figure I must be missing something obvious. How should I use these components? Sorry if this has an obvious solution. Thanks! 😄

**Comment by prateekbh** [comment]
TBH i've never played with permanent drawer, but are you saying the drawer is z-indexed on top of the grid?

**Comment by Jamdan2** [comment]
No, I mean with no additional styling, the drawer blocks the layout grid, and bumps it lower on the y axis, like this:

--------
       |
drawer |
       |
       |
       |
---------------------------------
 layout grid

I did find a fix using flex boxes. But aren't they supposed to work together by default? Or am I mistaken? By the way this also applies to the persistent drawer when it is opened.

**Comment by cromefire** [comment]
Flex boxes work really well everywhere, you just have to handle smaller screens yourself with thing like media queries
