### ISSUE TITLE
Add mdc-tab/scroller packages

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#999]
Mdc-tab-bar's styles are segregated into separate packages, we need to add these packages for their style.css or just copy these styles into mdc-tab-bar's.

Later might be easier

**Comment by prateekbh** [comment]
@cromefire can u take this up?

**Comment by cromefire** [comment]
So the style from scrolled just have to end up in the Tab directory?

**Comment by prateekbh** [comment]
Well I thought about this and adding the packages would be better as our script will copy the case and scss. No need to implement the js

**Comment by cromefire** [comment]
> No need to implement the js

Didn't implement any js See here #1002
